var hierarchy =
[
    [ "imagepy.tools.Measure.angle2_tol.Angle", "classimagepy_1_1tools_1_1_measure_1_1angle2__tol_1_1_angle.html", null ],
    [ "imagepy.tools.Measure.angle_tol.Angle", "classimagepy_1_1tools_1_1_measure_1_1angle__tol_1_1_angle.html", null ],
    [ "imagepy.tools.Measure.area_tol.Area", "classimagepy_1_1tools_1_1_measure_1_1area__tol_1_1_area.html", null ],
    [ "AuiDefaultDockArt", null, [
      [ "imagepy.ui.canvasframe.ImgArtProvider", "classimagepy_1_1ui_1_1canvasframe_1_1_img_art_provider.html", null ]
    ] ],
    [ "AuiNotebook", null, [
      [ "imagepy.ui.tableframe.TableNoteBook", "classimagepy_1_1ui_1_1tableframe_1_1_table_note_book.html", null ]
    ] ],
    [ "AuiNotebook", null, [
      [ "imagepy.ui.canvasframe.CanvasNoteBook", "classimagepy_1_1ui_1_1canvasframe_1_1_canvas_note_book.html", null ]
    ] ],
    [ "imagepy.ui.canvasframe.VirturlCanvas.Canvas", "classimagepy_1_1ui_1_1canvasframe_1_1_virturl_canvas_1_1_canvas.html", null ],
    [ "imagepy.core.manager.clipbdmanager.ClipBoardManager", "classimagepy_1_1core_1_1manager_1_1clipbdmanager_1_1_clip_board_manager.html", null ],
    [ "imagepy.core.manager.colormanager.ColorManager", "classimagepy_1_1core_1_1manager_1_1colormanager_1_1_color_manager.html", null ],
    [ "imagepy.core.manager.configmanager.ConfigManager", "classimagepy_1_1core_1_1manager_1_1configmanager_1_1_config_manager.html", null ],
    [ "imagepy.tools.Measure.coordinate_tol.Coordinate", "classimagepy_1_1tools_1_1_measure_1_1coordinate__tol_1_1_coordinate.html", null ],
    [ "imagepy.menus.Image.Stack.orthogonal_plg.Cross", "classimagepy_1_1menus_1_1_image_1_1_stack_1_1orthogonal__plg_1_1_cross.html", null ],
    [ "Dialog", null, [
      [ "imagepy.ui.panelconfig.ParaDialog", "classimagepy_1_1ui_1_1panelconfig_1_1_para_dialog.html", [
        [ "imagepy.menus.Image.Adjust.brightcons_plg.ThresholdDialog", "classimagepy_1_1menus_1_1_image_1_1_adjust_1_1brightcons__plg_1_1_threshold_dialog.html", null ],
        [ "imagepy.menus.Image.Adjust.colorbalance_plg.BalanceDialog", "classimagepy_1_1menus_1_1_image_1_1_adjust_1_1colorbalance__plg_1_1_balance_dialog.html", null ],
        [ "imagepy.menus.Image.Adjust.colorstairs_plg.StairsDialog", "classimagepy_1_1menus_1_1_image_1_1_adjust_1_1colorstairs__plg_1_1_stairs_dialog.html", null ],
        [ "imagepy.menus.Image.Adjust.graystairs_plg.ThresholdDialog", "classimagepy_1_1menus_1_1_image_1_1_adjust_1_1graystairs__plg_1_1_threshold_dialog.html", null ],
        [ "imagepy.menus.Image.Adjust.threshold_plg.ThresholdDialog", "classimagepy_1_1menus_1_1_image_1_1_adjust_1_1threshold__plg_1_1_threshold_dialog.html", null ],
        [ "imagepy.menus.Image.setscale_plg.ScaleDialog", "classimagepy_1_1menus_1_1_image_1_1setscale__plg_1_1_scale_dialog.html", null ]
      ] ],
      [ "imagepy.ui.propertygrid.GridDialog", "classimagepy_1_1ui_1_1propertygrid_1_1_grid_dialog.html", null ]
    ] ],
    [ "dict", null, [
      [ "imagepy.menus.Plugins.Manager.console_wgt.Macros", "classimagepy_1_1menus_1_1_plugins_1_1_manager_1_1console__wgt_1_1_macros.html", null ]
    ] ],
    [ "imagepy.tools.Measure.distance_tol.Distance", "classimagepy_1_1tools_1_1_measure_1_1distance__tol_1_1_distance.html", null ],
    [ "imagepy.core.manager.documentmanager.DocumentManager", "classimagepy_1_1core_1_1manager_1_1documentmanager_1_1_document_manager.html", null ],
    [ "FileDropTarget", null, [
      [ "imagepy.ui.mainframe.FileDrop", "classimagepy_1_1ui_1_1mainframe_1_1_file_drop.html", null ]
    ] ],
    [ "imagepy.core.engine.filter.Filter", "classimagepy_1_1core_1_1engine_1_1filter_1_1_filter.html", [
      [ "imagepy.menus.Analysis.label_plg.Plugin", "classimagepy_1_1menus_1_1_analysis_1_1label__plg_1_1_plugin.html", null ],
      [ "imagepy.menus.Analysis.Pixel Cluster.cluster_plgs.ColorCluster", "classimagepy_1_1menus_1_1_analysis_1_1_pixel_01_cluster_1_1cluster__plgs_1_1_color_cluster.html", null ],
      [ "imagepy.menus.Analysis.Pixel Cluster.cluster_plgs.GrayCluster", "classimagepy_1_1menus_1_1_analysis_1_1_pixel_01_cluster_1_1cluster__plgs_1_1_gray_cluster.html", null ],
      [ "imagepy.menus.Analysis.Pixel Cluster.kmeans_plgs.K_mean", "classimagepy_1_1menus_1_1_analysis_1_1_pixel_01_cluster_1_1kmeans__plgs_1_1_k__mean.html", null ],
      [ "imagepy.menus.Analysis.Region Analysis.regionprops_plgs.PropertyMarker", "classimagepy_1_1menus_1_1_analysis_1_1_region_01_analysis_1_1regionprops__plgs_1_1_property_marker.html", null ],
      [ "imagepy.menus.Analysis.Region Analysis.regionprops_plgs.RegionFilter", "classimagepy_1_1menus_1_1_analysis_1_1_region_01_analysis_1_1regionprops__plgs_1_1_region_filter.html", null ],
      [ "imagepy.menus.Analysis.Region Analysis.statistic_plgs.IntensityFilter", "classimagepy_1_1menus_1_1_analysis_1_1_region_01_analysis_1_1statistic__plgs_1_1_intensity_filter.html", null ],
      [ "imagepy.menus.Analysis.Skeleton Network.graph_plgs.BuildGraph", "classimagepy_1_1menus_1_1_analysis_1_1_skeleton_01_network_1_1graph__plgs_1_1_build_graph.html", null ],
      [ "imagepy.menus.Analysis.Skeleton Network.graph_plgs.CutBranch", "classimagepy_1_1menus_1_1_analysis_1_1_skeleton_01_network_1_1graph__plgs_1_1_cut_branch.html", null ],
      [ "imagepy.menus.Analysis.Skeleton Network.graph_plgs.CutROI", "classimagepy_1_1menus_1_1_analysis_1_1_skeleton_01_network_1_1graph__plgs_1_1_cut_r_o_i.html", null ],
      [ "imagepy.menus.Analysis.Skeleton Network.graph_plgs.RemoveIsolate", "classimagepy_1_1menus_1_1_analysis_1_1_skeleton_01_network_1_1graph__plgs_1_1_remove_isolate.html", null ],
      [ "imagepy.menus.Edit.edit_plg.Clear", "classimagepy_1_1menus_1_1_edit_1_1edit__plg_1_1_clear.html", null ],
      [ "imagepy.menus.Edit.edit_plg.ClearOut", "classimagepy_1_1menus_1_1_edit_1_1edit__plg_1_1_clear_out.html", null ],
      [ "imagepy.menus.Edit.edit_plg.Fill", "classimagepy_1_1menus_1_1_edit_1_1edit__plg_1_1_fill.html", null ],
      [ "imagepy.menus.Edit.edit_plg.Invert", "classimagepy_1_1menus_1_1_edit_1_1edit__plg_1_1_invert.html", null ],
      [ "imagepy.menus.Edit.edit_plg.Sketch", "classimagepy_1_1menus_1_1_edit_1_1edit__plg_1_1_sketch.html", null ],
      [ "imagepy.menus.Image.Adjust.brightcons_plg.Plugin", "classimagepy_1_1menus_1_1_image_1_1_adjust_1_1brightcons__plg_1_1_plugin.html", null ],
      [ "imagepy.menus.Image.Adjust.colorbalance_plg.Plugin", "classimagepy_1_1menus_1_1_image_1_1_adjust_1_1colorbalance__plg_1_1_plugin.html", null ],
      [ "imagepy.menus.Image.Adjust.colorstairs_plg.Plugin", "classimagepy_1_1menus_1_1_image_1_1_adjust_1_1colorstairs__plg_1_1_plugin.html", null ],
      [ "imagepy.menus.Image.Adjust.curve_plg.Plugin", "classimagepy_1_1menus_1_1_image_1_1_adjust_1_1curve__plg_1_1_plugin.html", null ],
      [ "imagepy.menus.Image.Adjust.graystairs_plg.Plugin", "classimagepy_1_1menus_1_1_image_1_1_adjust_1_1graystairs__plg_1_1_plugin.html", null ],
      [ "imagepy.menus.Image.Adjust.histogram_plgs.Normalize", "classimagepy_1_1menus_1_1_image_1_1_adjust_1_1histogram__plgs_1_1_normalize.html", null ],
      [ "imagepy.menus.Image.Adjust.threshold_plg.Plugin", "classimagepy_1_1menus_1_1_image_1_1_adjust_1_1threshold__plg_1_1_plugin.html", null ],
      [ "imagepy.menus.Image.Transform.Transform_plgs.Rotate", "classimagepy_1_1menus_1_1_image_1_1_transform_1_1_transform__plgs_1_1_rotate.html", null ],
      [ "imagepy.menus.Image.Transform.Transform_plgs.Scale", "classimagepy_1_1menus_1_1_image_1_1_transform_1_1_transform__plgs_1_1_scale.html", null ],
      [ "imagepy.menus.Kit3D.Analysis 3D.surfacemeasure_plg.Plugin", "classimagepy_1_1menus_1_1_kit3_d_1_1_analysis_013_d_1_1surfacemeasure__plg_1_1_plugin.html", null ],
      [ "imagepy.menus.Kit3D.Filters 3D.filters3d_plgs.UPWatershed", "classimagepy_1_1menus_1_1_kit3_d_1_1_filters_013_d_1_1filters3d__plgs_1_1_u_p_watershed.html", null ],
      [ "imagepy.menus.Kit3D.Viewer 3D.surface_plgs.Surface3D", "classimagepy_1_1menus_1_1_kit3_d_1_1_viewer_013_d_1_1surface__plgs_1_1_surface3_d.html", null ],
      [ "imagepy.menus.Plugins.Games.crossstick_plg.Plugin", "classimagepy_1_1menus_1_1_plugins_1_1_games_1_1crossstick__plg_1_1_plugin.html", null ],
      [ "imagepy.menus.Plugins.New.demo_filter.Plugin", "classimagepy_1_1menus_1_1_plugins_1_1_new_1_1demo__filter_1_1_plugin.html", null ],
      [ "imagepy.menus.Process.Binary.binary_plgs.Closing", "classimagepy_1_1menus_1_1_process_1_1_binary_1_1binary__plgs_1_1_closing.html", null ],
      [ "imagepy.menus.Process.Binary.binary_plgs.Convex", "classimagepy_1_1menus_1_1_process_1_1_binary_1_1binary__plgs_1_1_convex.html", null ],
      [ "imagepy.menus.Process.Binary.binary_plgs.Dilation", "classimagepy_1_1menus_1_1_process_1_1_binary_1_1binary__plgs_1_1_dilation.html", null ],
      [ "imagepy.menus.Process.Binary.binary_plgs.Erosion", "classimagepy_1_1menus_1_1_process_1_1_binary_1_1binary__plgs_1_1_erosion.html", null ],
      [ "imagepy.menus.Process.Binary.binary_plgs.FillHoles", "classimagepy_1_1menus_1_1_process_1_1_binary_1_1binary__plgs_1_1_fill_holes.html", null ],
      [ "imagepy.menus.Process.Binary.binary_plgs.Opening", "classimagepy_1_1menus_1_1_process_1_1_binary_1_1binary__plgs_1_1_opening.html", null ],
      [ "imagepy.menus.Process.Binary.binary_plgs.Outline", "classimagepy_1_1menus_1_1_process_1_1_binary_1_1binary__plgs_1_1_outline.html", null ],
      [ "imagepy.menus.Process.Binary.distance_plgs.EDT", "classimagepy_1_1menus_1_1_process_1_1_binary_1_1distance__plgs_1_1_e_d_t.html", null ],
      [ "imagepy.menus.Process.Binary.distance_plgs.MedialAxis", "classimagepy_1_1menus_1_1_process_1_1_binary_1_1distance__plgs_1_1_medial_axis.html", null ],
      [ "imagepy.menus.Process.Binary.distance_plgs.Skeleton", "classimagepy_1_1menus_1_1_process_1_1_binary_1_1distance__plgs_1_1_skeleton.html", null ],
      [ "imagepy.menus.Process.Binary.distance_plgs.Voronoi", "classimagepy_1_1menus_1_1_process_1_1_binary_1_1distance__plgs_1_1_voronoi.html", null ],
      [ "imagepy.menus.Process.Binary.distance_plgs.Watershed", "classimagepy_1_1menus_1_1_process_1_1_binary_1_1distance__plgs_1_1_watershed.html", null ],
      [ "imagepy.menus.Process.Features.corner_plgs.Harris", "classimagepy_1_1menus_1_1_process_1_1_features_1_1corner__plgs_1_1_harris.html", null ],
      [ "imagepy.menus.Process.Features.corner_plgs.Kitchen", "classimagepy_1_1menus_1_1_process_1_1_features_1_1corner__plgs_1_1_kitchen.html", null ],
      [ "imagepy.menus.Process.Features.corner_plgs.Moravec", "classimagepy_1_1menus_1_1_process_1_1_features_1_1corner__plgs_1_1_moravec.html", null ],
      [ "imagepy.menus.Process.Features.corner_plgs.Tomasi", "classimagepy_1_1menus_1_1_process_1_1_features_1_1corner__plgs_1_1_tomasi.html", null ],
      [ "imagepy.menus.Process.Features.edge_plgs.Canny", "classimagepy_1_1menus_1_1_process_1_1_features_1_1edge__plgs_1_1_canny.html", null ],
      [ "imagepy.menus.Process.Features.ridge_plgs.Frangi", "classimagepy_1_1menus_1_1_process_1_1_features_1_1ridge__plgs_1_1_frangi.html", null ],
      [ "imagepy.menus.Process.Features.ridge_plgs.Hessian", "classimagepy_1_1menus_1_1_process_1_1_features_1_1ridge__plgs_1_1_hessian.html", null ],
      [ "imagepy.menus.Process.Features.ridge_plgs.Meijering", "classimagepy_1_1menus_1_1_process_1_1_features_1_1ridge__plgs_1_1_meijering.html", null ],
      [ "imagepy.menus.Process.Features.ridge_plgs.Sato", "classimagepy_1_1menus_1_1_process_1_1_features_1_1ridge__plgs_1_1_sato.html", null ],
      [ "imagepy.menus.Process.FFT.fft_plgs.IShift", "classimagepy_1_1menus_1_1_process_1_1_f_f_t_1_1fft__plgs_1_1_i_shift.html", null ],
      [ "imagepy.menus.Process.FFT.fft_plgs.Shift", "classimagepy_1_1menus_1_1_process_1_1_f_f_t_1_1fft__plgs_1_1_shift.html", null ],
      [ "imagepy.menus.Process.Filters.classic_plgs.DOG", "classimagepy_1_1menus_1_1_process_1_1_filters_1_1classic__plgs_1_1_d_o_g.html", null ],
      [ "imagepy.menus.Process.Filters.classic_plgs.Gaussian", "classimagepy_1_1menus_1_1_process_1_1_filters_1_1classic__plgs_1_1_gaussian.html", null ],
      [ "imagepy.menus.Process.Filters.classic_plgs.GaussianLaplace", "classimagepy_1_1menus_1_1_process_1_1_filters_1_1classic__plgs_1_1_gaussian_laplace.html", null ],
      [ "imagepy.menus.Process.Filters.classic_plgs.Laplace", "classimagepy_1_1menus_1_1_process_1_1_filters_1_1classic__plgs_1_1_laplace.html", null ],
      [ "imagepy.menus.Process.Filters.classic_plgs.LaplaceSharp", "classimagepy_1_1menus_1_1_process_1_1_filters_1_1classic__plgs_1_1_laplace_sharp.html", null ],
      [ "imagepy.menus.Process.Filters.classic_plgs.Maximum", "classimagepy_1_1menus_1_1_process_1_1_filters_1_1classic__plgs_1_1_maximum.html", null ],
      [ "imagepy.menus.Process.Filters.classic_plgs.Median", "classimagepy_1_1menus_1_1_process_1_1_filters_1_1classic__plgs_1_1_median.html", null ],
      [ "imagepy.menus.Process.Filters.classic_plgs.Minimum", "classimagepy_1_1menus_1_1_process_1_1_filters_1_1classic__plgs_1_1_minimum.html", null ],
      [ "imagepy.menus.Process.Filters.classic_plgs.Percent", "classimagepy_1_1menus_1_1_process_1_1_filters_1_1classic__plgs_1_1_percent.html", null ],
      [ "imagepy.menus.Process.Filters.classic_plgs.Prewitt", "classimagepy_1_1menus_1_1_process_1_1_filters_1_1classic__plgs_1_1_prewitt.html", null ],
      [ "imagepy.menus.Process.Filters.classic_plgs.Sobel", "classimagepy_1_1menus_1_1_process_1_1_filters_1_1classic__plgs_1_1_sobel.html", null ],
      [ "imagepy.menus.Process.Filters.classic_plgs.Uniform", "classimagepy_1_1menus_1_1_process_1_1_filters_1_1classic__plgs_1_1_uniform.html", null ],
      [ "imagepy.menus.Process.Filters.classic_plgs.USM", "classimagepy_1_1menus_1_1_process_1_1_filters_1_1classic__plgs_1_1_u_s_m.html", null ],
      [ "imagepy.menus.Process.Filters.classic_plgs.Variance", "classimagepy_1_1menus_1_1_process_1_1_filters_1_1classic__plgs_1_1_variance.html", null ],
      [ "imagepy.menus.Process.Hydrology.hydrology_plgs.ARidge", "classimagepy_1_1menus_1_1_process_1_1_hydrology_1_1hydrology__plgs_1_1_a_ridge.html", null ],
      [ "imagepy.menus.Process.Hydrology.hydrology_plgs.FindMax", "classimagepy_1_1menus_1_1_process_1_1_hydrology_1_1hydrology__plgs_1_1_find_max.html", null ],
      [ "imagepy.menus.Process.Hydrology.hydrology_plgs.FindMin", "classimagepy_1_1menus_1_1_process_1_1_hydrology_1_1hydrology__plgs_1_1_find_min.html", null ],
      [ "imagepy.menus.Process.Hydrology.hydrology_plgs.IsoLine", "classimagepy_1_1menus_1_1_process_1_1_hydrology_1_1hydrology__plgs_1_1_iso_line.html", null ],
      [ "imagepy.menus.Process.Hydrology.hydrology_plgs.ROIWatershed", "classimagepy_1_1menus_1_1_process_1_1_hydrology_1_1hydrology__plgs_1_1_r_o_i_watershed.html", null ],
      [ "imagepy.menus.Process.Hydrology.hydrology_plgs.UPRidge", "classimagepy_1_1menus_1_1_process_1_1_hydrology_1_1hydrology__plgs_1_1_u_p_ridge.html", null ],
      [ "imagepy.menus.Process.Hydrology.hydrology_plgs.UPWatershed", "classimagepy_1_1menus_1_1_process_1_1_hydrology_1_1hydrology__plgs_1_1_u_p_watershed.html", null ],
      [ "imagepy.menus.Process.Hydrology.hydrology_plgs.Watershed", "classimagepy_1_1menus_1_1_process_1_1_hydrology_1_1hydrology__plgs_1_1_watershed.html", null ],
      [ "imagepy.menus.Process.Math.math_plgs.Add", "classimagepy_1_1menus_1_1_process_1_1_math_1_1math__plgs_1_1_add.html", null ],
      [ "imagepy.menus.Process.Math.math_plgs.Gamma", "classimagepy_1_1menus_1_1_process_1_1_math_1_1math__plgs_1_1_gamma.html", null ],
      [ "imagepy.menus.Process.Math.math_plgs.Max", "classimagepy_1_1menus_1_1_process_1_1_math_1_1math__plgs_1_1_max.html", null ],
      [ "imagepy.menus.Process.Math.math_plgs.Min", "classimagepy_1_1menus_1_1_process_1_1_math_1_1math__plgs_1_1_min.html", null ],
      [ "imagepy.menus.Process.Math.math_plgs.Multiply", "classimagepy_1_1menus_1_1_process_1_1_math_1_1math__plgs_1_1_multiply.html", null ],
      [ "imagepy.menus.Process.Math.math_plgs.Sqrt", "classimagepy_1_1menus_1_1_process_1_1_math_1_1math__plgs_1_1_sqrt.html", null ],
      [ "imagepy.menus.Process.Math.math_plgs.Subtract", "classimagepy_1_1menus_1_1_process_1_1_math_1_1math__plgs_1_1_subtract.html", null ],
      [ "imagepy.menus.Process.repair_plg.Plugin", "classimagepy_1_1menus_1_1_process_1_1repair__plg_1_1_plugin.html", null ],
      [ "imagepy.menus.Process.Segment.active_plgs.ChanVese", "classimagepy_1_1menus_1_1_process_1_1_segment_1_1active__plgs_1_1_chan_vese.html", null ],
      [ "imagepy.menus.Process.Segment.active_plgs.MorphChanVese", "classimagepy_1_1menus_1_1_process_1_1_segment_1_1active__plgs_1_1_morph_chan_vese.html", null ],
      [ "imagepy.menus.Process.Segment.active_plgs.MorphGeoChanVese", "classimagepy_1_1menus_1_1_process_1_1_segment_1_1active__plgs_1_1_morph_geo_chan_vese.html", null ],
      [ "imagepy.menus.Process.Segment.active_plgs.MorphGeoRoi", "classimagepy_1_1menus_1_1_process_1_1_segment_1_1active__plgs_1_1_morph_geo_roi.html", null ],
      [ "imagepy.menus.Process.Segment.active_plgs.RandomWalker", "classimagepy_1_1menus_1_1_process_1_1_segment_1_1active__plgs_1_1_random_walker.html", null ],
      [ "imagepy.menus.Process.Segment.shift_plgs.Felzenszwalb", "classimagepy_1_1menus_1_1_process_1_1_segment_1_1shift__plgs_1_1_felzenszwalb.html", null ],
      [ "imagepy.menus.Process.Segment.shift_plgs.Quickshift", "classimagepy_1_1menus_1_1_process_1_1_segment_1_1shift__plgs_1_1_quickshift.html", null ],
      [ "imagepy.menus.Process.Segment.shift_plgs.SLIC", "classimagepy_1_1menus_1_1_process_1_1_segment_1_1shift__plgs_1_1_s_l_i_c.html", null ],
      [ "imagepy.menus.Process.Threshold.threshold_plgs.Auto", "classimagepy_1_1menus_1_1_process_1_1_threshold_1_1threshold__plgs_1_1_auto.html", null ],
      [ "imagepy.menus.Process.Threshold.threshold_plgs.Hysteresis", "classimagepy_1_1menus_1_1_process_1_1_threshold_1_1threshold__plgs_1_1_hysteresis.html", null ],
      [ "imagepy.menus.Process.Threshold.threshold_plgs.Local", "classimagepy_1_1menus_1_1_process_1_1_threshold_1_1threshold__plgs_1_1_local.html", null ],
      [ "imagepy.menus.Process.Threshold.threshold_plgs.Niblack", "classimagepy_1_1menus_1_1_process_1_1_threshold_1_1threshold__plgs_1_1_niblack.html", null ],
      [ "imagepy.menus.Process.Threshold.threshold_plgs.Sauvola", "classimagepy_1_1menus_1_1_process_1_1_threshold_1_1threshold__plgs_1_1_sauvola.html", null ],
      [ "imagepy.tools.Transform.rotate_tol.Plugin", "classimagepy_1_1tools_1_1_transform_1_1rotate__tol_1_1_plugin.html", null ],
      [ "imagepy.tools.Transform.scale_tol.Plugin", "classimagepy_1_1tools_1_1_transform_1_1scale__tol_1_1_plugin.html", null ]
    ] ],
    [ "Frame", null, [
      [ "imagepy.core.myvi.frame3d.Frame3D", "classimagepy_1_1core_1_1myvi_1_1frame3d_1_1_frame3_d.html", null ],
      [ "imagepy.menus.Analysis.statistic_plg.HistogramFrame", "classimagepy_1_1menus_1_1_analysis_1_1statistic__plg_1_1_histogram_frame.html", null ],
      [ "imagepy.ui.canvasframe.CanvasFrame", "classimagepy_1_1ui_1_1canvasframe_1_1_canvas_frame.html", null ],
      [ "imagepy.ui.logwindow.TextLog", "classimagepy_1_1ui_1_1logwindow_1_1_text_log.html", null ],
      [ "imagepy.ui.mainframe.ImagePy", "classimagepy_1_1ui_1_1mainframe_1_1_image_py.html", null ],
      [ "imagepy.ui.mkdownwindow.MkDownWindow", "classimagepy_1_1ui_1_1mkdownwindow_1_1_mk_down_window.html", null ],
      [ "imagepy.ui.plotwindow.PlotFrame", "classimagepy_1_1ui_1_1plotwindow_1_1_plot_frame.html", null ],
      [ "imagepy.ui.tableframe.TableFrame", "classimagepy_1_1ui_1_1tableframe_1_1_table_frame.html", null ]
    ] ],
    [ "imagepy.core.engine.free.Free", "classimagepy_1_1core_1_1engine_1_1free_1_1_free.html", [
      [ "imagepy.core.util.fileio.Reader", "classimagepy_1_1core_1_1util_1_1fileio_1_1_reader.html", null ],
      [ "imagepy.core.util.tableio.Reader", "classimagepy_1_1core_1_1util_1_1tableio_1_1_reader.html", null ],
      [ "imagepy.core.util.testdata.TestData", "classimagepy_1_1core_1_1util_1_1testdata_1_1_test_data.html", null ],
      [ "imagepy.menus.File.exit_plg.Plugin", "classimagepy_1_1menus_1_1_file_1_1exit__plg_1_1_plugin.html", null ],
      [ "imagepy.menus.File.Import.raw_plg.Plugin", "classimagepy_1_1menus_1_1_file_1_1_import_1_1raw__plg_1_1_plugin.html", null ],
      [ "imagepy.menus.File.Import.roi_plg.Plugin", "classimagepy_1_1menus_1_1_file_1_1_import_1_1roi__plg_1_1_plugin.html", null ],
      [ "imagepy.menus.File.Import.sequence_plg.Plugin", "classimagepy_1_1menus_1_1_file_1_1_import_1_1sequence__plg_1_1_plugin.html", null ],
      [ "imagepy.menus.File.new_plg.Plugin", "classimagepy_1_1menus_1_1_file_1_1new__plg_1_1_plugin.html", null ],
      [ "imagepy.menus.File.open_plg.OpenUrl", "classimagepy_1_1menus_1_1_file_1_1open__plg_1_1_open_url.html", null ],
      [ "imagepy.menus.File.Samples ImageJ.ijsample_plgs.IJImg", "classimagepy_1_1menus_1_1_file_1_1_samples_01_image_j_1_1ijsample__plgs_1_1_i_j_img.html", null ],
      [ "imagepy.menus.File.Samples Local.samples_plgs.Data", "classimagepy_1_1menus_1_1_file_1_1_samples_01_local_1_1samples__plgs_1_1_data.html", null ],
      [ "imagepy.menus.Help.Help_plgs.About", "classimagepy_1_1menus_1_1_help_1_1_help__plgs_1_1_about.html", null ],
      [ "imagepy.menus.Help.Help_plgs.Home", "classimagepy_1_1menus_1_1_help_1_1_help__plgs_1_1_home.html", null ],
      [ "imagepy.menus.Help.Help_plgs.Topic", "classimagepy_1_1menus_1_1_help_1_1_help__plgs_1_1_topic.html", null ],
      [ "imagepy.menus.Help.Language.language_plgs.CleanDictionary", "classimagepy_1_1menus_1_1_help_1_1_language_1_1language__plgs_1_1_clean_dictionary.html", null ],
      [ "imagepy.menus.Help.Language.language_plgs.Language", "classimagepy_1_1menus_1_1_help_1_1_language_1_1language__plgs_1_1_language.html", null ],
      [ "imagepy.menus.Help.Language.language_plgs.NewLanguage", "classimagepy_1_1menus_1_1_help_1_1_language_1_1language__plgs_1_1_new_language.html", null ],
      [ "imagepy.menus.Help.Language.language_plgs.UpdateDictionary", "classimagepy_1_1menus_1_1_help_1_1_language_1_1language__plgs_1_1_update_dictionary.html", null ],
      [ "imagepy.menus.Image.Lookup table.lookuptables_plg.Plugin", "classimagepy_1_1menus_1_1_image_1_1_lookup_01table_1_1lookuptables__plg_1_1_plugin.html", null ],
      [ "imagepy.menus.Image.Mark.mark_plgs.Setting", "classimagepy_1_1menus_1_1_image_1_1_mark_1_1mark__plgs_1_1_setting.html", null ],
      [ "imagepy.menus.Kit3D.Viewer 3D.demo_plgs.Balls", "classimagepy_1_1menus_1_1_kit3_d_1_1_viewer_013_d_1_1demo__plgs_1_1_balls.html", null ],
      [ "imagepy.menus.Kit3D.Viewer 3D.demo_plgs.Decoration", "classimagepy_1_1menus_1_1_kit3_d_1_1_viewer_013_d_1_1demo__plgs_1_1_decoration.html", null ],
      [ "imagepy.menus.Kit3D.Viewer 3D.demo_plgs.Lines", "classimagepy_1_1menus_1_1_kit3_d_1_1_viewer_013_d_1_1demo__plgs_1_1_lines.html", null ],
      [ "imagepy.menus.Kit3D.Viewer 3D.surface_plgs.Show", "classimagepy_1_1menus_1_1_kit3_d_1_1_viewer_013_d_1_1surface__plgs_1_1_show.html", null ],
      [ "imagepy.menus.Plugins.Games.lifegame_plg.Plugin", "classimagepy_1_1menus_1_1_plugins_1_1_games_1_1lifegame__plg_1_1_plugin.html", null ],
      [ "imagepy.menus.Plugins.Install.installpkg_plgs.Install", "classimagepy_1_1menus_1_1_plugins_1_1_install_1_1installpkg__plgs_1_1_install.html", null ],
      [ "imagepy.menus.Plugins.Install.installpkg_plgs.List", "classimagepy_1_1menus_1_1_plugins_1_1_install_1_1installpkg__plgs_1_1_list.html", null ],
      [ "imagepy.menus.Plugins.Install.installplg_plgs.Install", "classimagepy_1_1menus_1_1_plugins_1_1_install_1_1installplg__plgs_1_1_install.html", null ],
      [ "imagepy.menus.Plugins.Install.installplg_plgs.List", "classimagepy_1_1menus_1_1_plugins_1_1_install_1_1installplg__plgs_1_1_list.html", null ],
      [ "imagepy.menus.Plugins.Macros.recorder_plg.Plugin", "classimagepy_1_1menus_1_1_plugins_1_1_macros_1_1recorder__plg_1_1_plugin.html", null ],
      [ "imagepy.menus.Plugins.New.demo_free.Plugin", "classimagepy_1_1menus_1_1_plugins_1_1_new_1_1demo__free_1_1_plugin.html", null ],
      [ "imagepy.menus.Plugins.New.new_plg.NewFilter", "classimagepy_1_1menus_1_1_plugins_1_1_new_1_1new__plg_1_1_new_filter.html", null ],
      [ "imagepy.menus.Plugins.New.new_plg.NewFree", "classimagepy_1_1menus_1_1_plugins_1_1_new_1_1new__plg_1_1_new_free.html", null ],
      [ "imagepy.menus.Plugins.New.new_plg.NewSimple", "classimagepy_1_1menus_1_1_plugins_1_1_new_1_1new__plg_1_1_new_simple.html", null ],
      [ "imagepy.menus.Plugins.New.new_plg.NewTool", "classimagepy_1_1menus_1_1_plugins_1_1_new_1_1new__plg_1_1_new_tool.html", null ],
      [ "imagepy.menus.Plugins.screencap_plg.Plugin", "classimagepy_1_1menus_1_1_plugins_1_1screencap__plg_1_1_plugin.html", null ],
      [ "imagepy.menus.Plugins.update_plg.Refresh", "classimagepy_1_1menus_1_1_plugins_1_1update__plg_1_1_refresh.html", null ],
      [ "imagepy.menus.Plugins.update_plg.Update", "classimagepy_1_1menus_1_1_plugins_1_1update__plg_1_1_update.html", null ],
      [ "imagepy.menus.Selection.select_plg.Setting", "classimagepy_1_1menus_1_1_selection_1_1select__plg_1_1_setting.html", null ],
      [ "imagepy.menus.Table.Universal Generator.gnerator_plgs.Calendar", "classimagepy_1_1menus_1_1_table_1_1_universal_01_generator_1_1gnerator__plgs_1_1_calendar.html", null ],
      [ "imagepy.menus.Table.Universal Generator.gnerator_plgs.One", "classimagepy_1_1menus_1_1_table_1_1_universal_01_generator_1_1gnerator__plgs_1_1_one.html", null ],
      [ "imagepy.menus.Table.Universal Generator.gnerator_plgs.Random01", "classimagepy_1_1menus_1_1_table_1_1_universal_01_generator_1_1gnerator__plgs_1_1_random01.html", null ],
      [ "imagepy.menus.Table.Universal Generator.gnerator_plgs.RandomN", "classimagepy_1_1menus_1_1_table_1_1_universal_01_generator_1_1gnerator__plgs_1_1_random_n.html", null ],
      [ "imagepy.menus.Window.widgets_plgs.TableWindow", "classimagepy_1_1menus_1_1_window_1_1widgets__plgs_1_1_table_window.html", null ],
      [ "imagepy.menus.Window.widgets_plgs.ToolBar", "classimagepy_1_1menus_1_1_window_1_1widgets__plgs_1_1_tool_bar.html", null ],
      [ "imagepy.menus.Window.widgets_plgs.Widgets", "classimagepy_1_1menus_1_1_window_1_1widgets__plgs_1_1_widgets.html", null ],
      [ "imagepy.menus.Window.Windows Style.style_plgs.ImageJStyle", "classimagepy_1_1menus_1_1_window_1_1_windows_01_style_1_1style__plgs_1_1_image_j_style.html", null ],
      [ "imagepy.menus.Window.Windows Style.style_plgs.ImagePyStyle", "classimagepy_1_1menus_1_1_window_1_1_windows_01_style_1_1style__plgs_1_1_image_py_style.html", null ],
      [ "imagepy.menus.Window.windowskiller_plg.ImageKiller", "classimagepy_1_1menus_1_1_window_1_1windowskiller__plg_1_1_image_killer.html", null ],
      [ "imagepy.menus.Window.windowskiller_plg.TableKiller", "classimagepy_1_1menus_1_1_window_1_1windowskiller__plg_1_1_table_killer.html", null ],
      [ "imagepy.menus.Window.windowskiller_plg.TextKiller", "classimagepy_1_1menus_1_1_window_1_1windowskiller__plg_1_1_text_killer.html", null ]
    ] ],
    [ "imagepy.core.mark.mark.GeometryMark", "classimagepy_1_1core_1_1mark_1_1mark_1_1_geometry_mark.html", null ],
    [ "GLCanvas", null, [
      [ "imagepy.core.myvi.canvas3d.Canvas3D", "classimagepy_1_1core_1_1myvi_1_1canvas3d_1_1_canvas3_d.html", null ]
    ] ],
    [ "Grid", null, [
      [ "imagepy.ui.tablewindow.GridBase", "classimagepy_1_1ui_1_1tablewindow_1_1_grid_base.html", null ]
    ] ],
    [ "GridCellRenderer", null, [
      [ "imagepy.ui.tablewindow.MegaFontRenderer", "classimagepy_1_1ui_1_1tablewindow_1_1_mega_font_renderer.html", null ]
    ] ],
    [ "GridTableBase", null, [
      [ "imagepy.ui.tablewindow.TableBase", "classimagepy_1_1ui_1_1tablewindow_1_1_table_base.html", null ]
    ] ],
    [ "imagepy.core.manager.windowmanager.ImageManager", "classimagepy_1_1core_1_1manager_1_1windowmanager_1_1_image_manager.html", null ],
    [ "imagepy.core.wraper.imageplus.ImagePlus", "classimagepy_1_1core_1_1wraper_1_1imageplus_1_1_image_plus.html", null ],
    [ "imagepy.core.manager.languagemanager.LanguageManager", "classimagepy_1_1core_1_1manager_1_1languagemanager_1_1_language_manager.html", null ],
    [ "imagepy.tools.Standard.freeline_tol.Linebuf", "classimagepy_1_1tools_1_1_standard_1_1freeline__tol_1_1_linebuf.html", null ],
    [ "imagepy.tools.Standard.line_tol.Linebuf", "classimagepy_1_1tools_1_1_standard_1_1line__tol_1_1_linebuf.html", null ],
    [ "ListCtrl", null, [
      [ "imagepy.menus.Plugins.Contribute.pmanager_wgt.VirtualListCtrl", "classimagepy_1_1menus_1_1_plugins_1_1_contribute_1_1pmanager__wgt_1_1_virtual_list_ctrl.html", null ],
      [ "imagepy.menus.Plugins.Manager.plglist_wgt.VirtualListCtrl", "classimagepy_1_1menus_1_1_plugins_1_1_manager_1_1plglist__wgt_1_1_virtual_list_ctrl.html", null ],
      [ "imagepy.menus.Plugins.Manager.shotcut_wgt.VirtualListCtrl", "classimagepy_1_1menus_1_1_plugins_1_1_manager_1_1shotcut__wgt_1_1_virtual_list_ctrl.html", null ],
      [ "imagepy.menus.Selection.roiwindow_wgt.VirtualListCtrl", "classimagepy_1_1menus_1_1_selection_1_1roiwindow__wgt_1_1_virtual_list_ctrl.html", null ]
    ] ],
    [ "imagepy.core.engine.macros.Macros", "classimagepy_1_1core_1_1engine_1_1macros_1_1_macros.html", null ],
    [ "imagepy.core.myvi.manager.Manager", "classimagepy_1_1core_1_1myvi_1_1manager_1_1_manager.html", null ],
    [ "imagepy.menus.Analysis.Skeleton Network.graph_plgs.Mark", "classimagepy_1_1menus_1_1_analysis_1_1_skeleton_01_network_1_1graph__plgs_1_1_mark.html", null ],
    [ "imagepy.menus.Analysis.statistic_plg.Mark", "classimagepy_1_1menus_1_1_analysis_1_1statistic__plg_1_1_mark.html", null ],
    [ "imagepy.tools.Network.graphcut_tol.Mark", "classimagepy_1_1tools_1_1_network_1_1graphcut__tol_1_1_mark.html", null ],
    [ "imagepy.tools.Network.graphpen_tol.Mark", "classimagepy_1_1tools_1_1_network_1_1graphpen__tol_1_1_mark.html", null ],
    [ "imagepy.menus.Analysis.Region Analysis.statistic_plgs.Mark", "classimagepy_1_1menus_1_1_analysis_1_1_region_01_analysis_1_1statistic__plgs_1_1_mark.html", null ],
    [ "imagepy.core.myvi.manager.MarkText", "classimagepy_1_1core_1_1myvi_1_1manager_1_1_mark_text.html", null ],
    [ "imagepy.core.engine.mkdown.MkDown", "classimagepy_1_1core_1_1engine_1_1mkdown_1_1_mk_down.html", null ],
    [ "OwnerDrawnComboBox", null, [
      [ "imagepy.ui.widgets.colormap.CMapSelCtrl", "classimagepy_1_1ui_1_1widgets_1_1colormap_1_1_c_map_sel_ctrl.html", null ]
    ] ],
    [ "imagepy.core.draw.paint.Paint", "classimagepy_1_1core_1_1draw_1_1paint_1_1_paint.html", null ],
    [ "Panel", null, [
      [ "imagepy.core.myvi.canvas3d.Viewer3D", "classimagepy_1_1core_1_1myvi_1_1canvas3d_1_1_viewer3_d.html", null ],
      [ "imagepy.menus.Plugins.Contribute.pmanager_wgt.Plugin", "classimagepy_1_1menus_1_1_plugins_1_1_contribute_1_1pmanager__wgt_1_1_plugin.html", null ],
      [ "imagepy.menus.Plugins.Macros.recorder_wgt.Plugin", "classimagepy_1_1menus_1_1_plugins_1_1_macros_1_1recorder__wgt_1_1_plugin.html", null ],
      [ "imagepy.menus.Plugins.Manager.console_wgt.Plugin", "classimagepy_1_1menus_1_1_plugins_1_1_manager_1_1console__wgt_1_1_plugin.html", null ],
      [ "imagepy.menus.Plugins.Manager.plglist_wgt.Plugin", "classimagepy_1_1menus_1_1_plugins_1_1_manager_1_1plglist__wgt_1_1_plugin.html", null ],
      [ "imagepy.menus.Plugins.Manager.plgtree_wgt.Plugin", "classimagepy_1_1menus_1_1_plugins_1_1_manager_1_1plgtree__wgt_1_1_plugin.html", null ],
      [ "imagepy.menus.Plugins.Manager.shotcut_wgt.Plugin", "classimagepy_1_1menus_1_1_plugins_1_1_manager_1_1shotcut__wgt_1_1_plugin.html", null ],
      [ "imagepy.menus.Plugins.Manager.toltree_wgt.Plugin", "classimagepy_1_1menus_1_1_plugins_1_1_manager_1_1toltree__wgt_1_1_plugin.html", null ],
      [ "imagepy.menus.Selection.roiwindow_wgt.Plugin", "classimagepy_1_1menus_1_1_selection_1_1roiwindow__wgt_1_1_plugin.html", null ],
      [ "imagepy.menus.Window.develop_wgts.DevelopToolSute", "classimagepy_1_1menus_1_1_window_1_1develop__wgts_1_1_develop_tool_sute.html", null ],
      [ "imagepy.ui.canvas.Canvas", "classimagepy_1_1ui_1_1canvas_1_1_canvas.html", null ],
      [ "imagepy.ui.canvasframe.CanvasPanel", "classimagepy_1_1ui_1_1canvasframe_1_1_canvas_panel.html", null ],
      [ "imagepy.ui.mkdownwindow.HtmlPanel", "classimagepy_1_1ui_1_1mkdownwindow_1_1_html_panel.html", null ],
      [ "imagepy.ui.plotwindow.LineCanvas", "classimagepy_1_1ui_1_1plotwindow_1_1_line_canvas.html", null ],
      [ "imagepy.ui.tableframe.TablePanel", "classimagepy_1_1ui_1_1tableframe_1_1_table_panel.html", null ],
      [ "imagepy.ui.widgets.cmappanel.CMapPanel", "classimagepy_1_1ui_1_1widgets_1_1cmappanel_1_1_c_map_panel.html", null ],
      [ "imagepy.ui.widgets.colormap.CMapSelPanel", "classimagepy_1_1ui_1_1widgets_1_1colormap_1_1_c_map_sel_panel.html", [
        [ "imagepy.ui.widgets.advanced.ColorMap", "classimagepy_1_1ui_1_1widgets_1_1advanced_1_1_color_map.html", null ]
      ] ],
      [ "imagepy.ui.widgets.curvepanel.CurvePanel", "classimagepy_1_1ui_1_1widgets_1_1curvepanel_1_1_curve_panel.html", null ],
      [ "imagepy.ui.widgets.histpanel.HistCanvas", "classimagepy_1_1ui_1_1widgets_1_1histpanel_1_1_hist_canvas.html", null ],
      [ "imagepy.ui.widgets.normal.AnyType", "classimagepy_1_1ui_1_1widgets_1_1normal_1_1_any_type.html", null ],
      [ "imagepy.ui.widgets.normal.Check", "classimagepy_1_1ui_1_1widgets_1_1normal_1_1_check.html", null ],
      [ "imagepy.ui.widgets.normal.Choice", "classimagepy_1_1ui_1_1widgets_1_1normal_1_1_choice.html", [
        [ "imagepy.ui.widgets.advanced.ImageList", "classimagepy_1_1ui_1_1widgets_1_1advanced_1_1_image_list.html", null ],
        [ "imagepy.ui.widgets.advanced.TableField", "classimagepy_1_1ui_1_1widgets_1_1advanced_1_1_table_field.html", null ],
        [ "imagepy.ui.widgets.advanced.TableList", "classimagepy_1_1ui_1_1widgets_1_1advanced_1_1_table_list.html", null ]
      ] ],
      [ "imagepy.ui.widgets.normal.Choices", "classimagepy_1_1ui_1_1widgets_1_1normal_1_1_choices.html", [
        [ "imagepy.ui.widgets.advanced.TableFields", "classimagepy_1_1ui_1_1widgets_1_1advanced_1_1_table_fields.html", null ]
      ] ],
      [ "imagepy.ui.widgets.normal.ColorCtrl", "classimagepy_1_1ui_1_1widgets_1_1normal_1_1_color_ctrl.html", null ],
      [ "imagepy.ui.widgets.normal.FloatSlider", "classimagepy_1_1ui_1_1widgets_1_1normal_1_1_float_slider.html", null ],
      [ "imagepy.ui.widgets.normal.Label", "classimagepy_1_1ui_1_1widgets_1_1normal_1_1_label.html", null ],
      [ "imagepy.ui.widgets.normal.NumCtrl", "classimagepy_1_1ui_1_1widgets_1_1normal_1_1_num_ctrl.html", null ],
      [ "imagepy.ui.widgets.normal.TextCtrl", "classimagepy_1_1ui_1_1widgets_1_1normal_1_1_text_ctrl.html", null ],
      [ "imagepy.ui.widgets.viewport.ViewPort", "classimagepy_1_1ui_1_1widgets_1_1viewport_1_1_view_port.html", null ],
      [ "imagepy.ui.workflowwindow.WorkFlowPanel", "classimagepy_1_1ui_1_1workflowwindow_1_1_work_flow_panel.html", null ],
      [ "imagepy.widgets.histogram.curve_wgt.Plugin", "classimagepy_1_1widgets_1_1histogram_1_1curve__wgt_1_1_plugin.html", null ],
      [ "imagepy.widgets.histogram.histogram_wgt.Plugin", "classimagepy_1_1widgets_1_1histogram_1_1histogram__wgt_1_1_plugin.html", null ],
      [ "imagepy.widgets.navigator.navigator_wgt.Plugin", "classimagepy_1_1widgets_1_1navigator_1_1navigator__wgt_1_1_plugin.html", null ]
    ] ],
    [ "imagepy.core.manager.windowmanager.PlotManager", "classimagepy_1_1core_1_1manager_1_1windowmanager_1_1_plot_manager.html", null ],
    [ "imagepy.core.manager.pluginmanager.PluginsManager", "classimagepy_1_1core_1_1manager_1_1pluginmanager_1_1_plugins_manager.html", null ],
    [ "imagepy.tools.Standard.polygon_tol.Polygonbuf", "classimagepy_1_1tools_1_1_standard_1_1polygon__tol_1_1_polygonbuf.html", null ],
    [ "imagepy.tools.Measure.profile_tol.Profile", "classimagepy_1_1tools_1_1_measure_1_1profile__tol_1_1_profile.html", null ],
    [ "Reader", null, [
      [ "imagepy.menus.Table.Table IO.tableio_plgs.OpenCSV", "classimagepy_1_1menus_1_1_table_1_1_table_01_i_o_1_1tableio__plgs_1_1_open_c_s_v.html", null ],
      [ "imagepy.menus.Table.Table IO.tableio_plgs.OpenExcel", "classimagepy_1_1menus_1_1_table_1_1_table_01_i_o_1_1tableio__plgs_1_1_open_excel.html", null ]
    ] ],
    [ "Reader", null, [
      [ "imagepy.menus.File.BMP.bmp_plgs.OpenFile", "classimagepy_1_1menus_1_1_file_1_1_b_m_p_1_1bmp__plgs_1_1_open_file.html", null ],
      [ "imagepy.menus.File.DAT.dat_plgs.OpenFile", "classimagepy_1_1menus_1_1_file_1_1_d_a_t_1_1dat__plgs_1_1_open_file.html", null ],
      [ "imagepy.menus.File.DICOM.dicom_plgs.OpenFile", "classimagepy_1_1menus_1_1_file_1_1_d_i_c_o_m_1_1dicom__plgs_1_1_open_file.html", null ],
      [ "imagepy.menus.File.GIF.animate_plgs.OpenAnimate", "classimagepy_1_1menus_1_1_file_1_1_g_i_f_1_1animate__plgs_1_1_open_animate.html", null ],
      [ "imagepy.menus.File.GIF.gif_plgs.OpenFile", "classimagepy_1_1menus_1_1_file_1_1_g_i_f_1_1gif__plgs_1_1_open_file.html", null ],
      [ "imagepy.menus.File.JPG.jpg_plgs.OpenFile", "classimagepy_1_1menus_1_1_file_1_1_j_p_g_1_1jpg__plgs_1_1_open_file.html", null ],
      [ "imagepy.menus.File.MAT.mat_plgs.Open3D", "classimagepy_1_1menus_1_1_file_1_1_m_a_t_1_1mat__plgs_1_1_open3_d.html", null ],
      [ "imagepy.menus.File.MAT.mat_plgs.OpenFile", "classimagepy_1_1menus_1_1_file_1_1_m_a_t_1_1mat__plgs_1_1_open_file.html", null ],
      [ "imagepy.menus.File.Numpy.ndarray_plgs.Open3D", "classimagepy_1_1menus_1_1_file_1_1_numpy_1_1ndarray__plgs_1_1_open3_d.html", null ],
      [ "imagepy.menus.File.Numpy.ndarray_plgs.OpenFile", "classimagepy_1_1menus_1_1_file_1_1_numpy_1_1ndarray__plgs_1_1_open_file.html", null ],
      [ "imagepy.menus.File.open_plg.OpenFile", "classimagepy_1_1menus_1_1_file_1_1open__plg_1_1_open_file.html", null ],
      [ "imagepy.menus.File.PNG.png_plgs.OpenFile", "classimagepy_1_1menus_1_1_file_1_1_p_n_g_1_1png__plgs_1_1_open_file.html", null ],
      [ "imagepy.menus.File.TIF.tif3d_plgs.Open", "classimagepy_1_1menus_1_1_file_1_1_t_i_f_1_1tif3d__plgs_1_1_open.html", null ],
      [ "imagepy.menus.File.TIF.tif_plgs.OpenFile", "classimagepy_1_1menus_1_1_file_1_1_t_i_f_1_1tif__plgs_1_1_open_file.html", null ]
    ] ],
    [ "imagepy.core.manager.iomanager.ReaderManager", "classimagepy_1_1core_1_1manager_1_1iomanager_1_1_reader_manager.html", null ],
    [ "imagepy.core.engine.report.Report", "classimagepy_1_1core_1_1engine_1_1report_1_1_report.html", null ],
    [ "imagepy.menus.Analysis.Region Analysis.statistic_plgs.RGMark", "classimagepy_1_1menus_1_1_analysis_1_1_region_01_analysis_1_1statistic__plgs_1_1_r_g_mark.html", null ],
    [ "imagepy.core.roi.roi.ROI", "classimagepy_1_1core_1_1roi_1_1roi_1_1_r_o_i.html", [
      [ "imagepy.core.roi.lineroi.LineRoi", "classimagepy_1_1core_1_1roi_1_1lineroi_1_1_line_roi.html", null ],
      [ "imagepy.core.roi.ovalroi.OvalRoi", "classimagepy_1_1core_1_1roi_1_1ovalroi_1_1_oval_roi.html", null ],
      [ "imagepy.core.roi.pointroi.PointRoi", "classimagepy_1_1core_1_1roi_1_1pointroi_1_1_point_roi.html", null ],
      [ "imagepy.core.roi.polygonroi.PolygonRoi", "classimagepy_1_1core_1_1roi_1_1polygonroi_1_1_polygon_roi.html", null ],
      [ "imagepy.core.roi.rectangleroi.RectangleRoi", "classimagepy_1_1core_1_1roi_1_1rectangleroi_1_1_rectangle_roi.html", null ]
    ] ],
    [ "imagepy.core.manager.roimanager.RoiManager", "classimagepy_1_1core_1_1manager_1_1roimanager_1_1_roi_manager.html", null ],
    [ "imagepy.core.manager.shotcutmanager.ShotcutManager", "classimagepy_1_1core_1_1manager_1_1shotcutmanager_1_1_shotcut_manager.html", null ],
    [ "imagepy.core.engine.simple.Simple", "classimagepy_1_1core_1_1engine_1_1simple_1_1_simple.html", [
      [ "imagepy.core.util.fileio.Writer", "classimagepy_1_1core_1_1util_1_1fileio_1_1_writer.html", null ],
      [ "imagepy.menus.Analysis.Pixel Cluster.cluster_plgs.ColorCluster3D", "classimagepy_1_1menus_1_1_analysis_1_1_pixel_01_cluster_1_1cluster__plgs_1_1_color_cluster3_d.html", null ],
      [ "imagepy.menus.Analysis.Pixel Cluster.cluster_plgs.GrayCluster3D", "classimagepy_1_1menus_1_1_analysis_1_1_pixel_01_cluster_1_1cluster__plgs_1_1_gray_cluster3_d.html", null ],
      [ "imagepy.menus.Analysis.Pixel Cluster.statistic_plgs.ColorStatistic", "classimagepy_1_1menus_1_1_analysis_1_1_pixel_01_cluster_1_1statistic__plgs_1_1_color_statistic.html", null ],
      [ "imagepy.menus.Analysis.Pixel Cluster.statistic_plgs.GrayStatistic", "classimagepy_1_1menus_1_1_analysis_1_1_pixel_01_cluster_1_1statistic__plgs_1_1_gray_statistic.html", null ],
      [ "imagepy.menus.Analysis.Region Analysis.regionprops_plgs.RegionCounter", "classimagepy_1_1menus_1_1_analysis_1_1_region_01_analysis_1_1regionprops__plgs_1_1_region_counter.html", null ],
      [ "imagepy.menus.Analysis.Region Analysis.statistic_plgs.RegionStatistic", "classimagepy_1_1menus_1_1_analysis_1_1_region_01_analysis_1_1statistic__plgs_1_1_region_statistic.html", null ],
      [ "imagepy.menus.Analysis.Skeleton Network.graph_plgs.Remove2Node", "classimagepy_1_1menus_1_1_analysis_1_1_skeleton_01_network_1_1graph__plgs_1_1_remove2_node.html", null ],
      [ "imagepy.menus.Analysis.Skeleton Network.graph_plgs.ShortestPath", "classimagepy_1_1menus_1_1_analysis_1_1_skeleton_01_network_1_1graph__plgs_1_1_shortest_path.html", null ],
      [ "imagepy.menus.Analysis.Skeleton Network.graph_plgs.Statistic", "classimagepy_1_1menus_1_1_analysis_1_1_skeleton_01_network_1_1graph__plgs_1_1_statistic.html", null ],
      [ "imagepy.menus.Analysis.Skeleton Network.graph_plgs.Sumerise", "classimagepy_1_1menus_1_1_analysis_1_1_skeleton_01_network_1_1graph__plgs_1_1_sumerise.html", null ],
      [ "imagepy.menus.Analysis.statistic_plg.Frequence", "classimagepy_1_1menus_1_1_analysis_1_1statistic__plg_1_1_frequence.html", null ],
      [ "imagepy.menus.Analysis.statistic_plg.Histogram", "classimagepy_1_1menus_1_1_analysis_1_1statistic__plg_1_1_histogram.html", null ],
      [ "imagepy.menus.Analysis.statistic_plg.PointsValue", "classimagepy_1_1menus_1_1_analysis_1_1statistic__plg_1_1_points_value.html", null ],
      [ "imagepy.menus.Analysis.statistic_plg.Statistic", "classimagepy_1_1menus_1_1_analysis_1_1statistic__plg_1_1_statistic.html", null ],
      [ "imagepy.menus.Edit.edit_plg.Copy", "classimagepy_1_1menus_1_1_edit_1_1edit__plg_1_1_copy.html", null ],
      [ "imagepy.menus.Edit.edit_plg.Paste", "classimagepy_1_1menus_1_1_edit_1_1edit__plg_1_1_paste.html", null ],
      [ "imagepy.menus.Edit.edit_plg.Undo", "classimagepy_1_1menus_1_1_edit_1_1edit__plg_1_1_undo.html", null ],
      [ "imagepy.menus.File.Export.sequence_plg.Plugin", "classimagepy_1_1menus_1_1_file_1_1_export_1_1sequence__plg_1_1_plugin.html", null ],
      [ "imagepy.menus.File.GIF.animate_plgs.SaveAnimate", "classimagepy_1_1menus_1_1_file_1_1_g_i_f_1_1animate__plgs_1_1_save_animate.html", null ],
      [ "imagepy.menus.Image.Adjust.histogram_plgs.Match", "classimagepy_1_1menus_1_1_image_1_1_adjust_1_1histogram__plgs_1_1_match.html", null ],
      [ "imagepy.menus.Image.background_plg.BackgroundSelf", "classimagepy_1_1menus_1_1_image_1_1background__plg_1_1_background_self.html", null ],
      [ "imagepy.menus.Image.background_plg.SetBackground", "classimagepy_1_1menus_1_1_image_1_1background__plg_1_1_set_background.html", null ],
      [ "imagepy.menus.Image.canvassize_plg.Plugin", "classimagepy_1_1menus_1_1_image_1_1canvassize__plg_1_1_plugin.html", null ],
      [ "imagepy.menus.Image.Color.splitandmerge_plgs.RGB2", "classimagepy_1_1menus_1_1_image_1_1_color_1_1splitandmerge__plgs_1_1_r_g_b2.html", [
        [ "imagepy.menus.Image.Color.splitandmerge_plgs.RGB2CIE", "classimagepy_1_1menus_1_1_image_1_1_color_1_1splitandmerge__plgs_1_1_r_g_b2_c_i_e.html", null ],
        [ "imagepy.menus.Image.Color.splitandmerge_plgs.RGB2HSV", "classimagepy_1_1menus_1_1_image_1_1_color_1_1splitandmerge__plgs_1_1_r_g_b2_h_s_v.html", null ],
        [ "imagepy.menus.Image.Color.splitandmerge_plgs.RGB2Lab", "classimagepy_1_1menus_1_1_image_1_1_color_1_1splitandmerge__plgs_1_1_r_g_b2_lab.html", null ],
        [ "imagepy.menus.Image.Color.splitandmerge_plgs.RGB2LUV", "classimagepy_1_1menus_1_1_image_1_1_color_1_1splitandmerge__plgs_1_1_r_g_b2_l_u_v.html", null ],
        [ "imagepy.menus.Image.Color.splitandmerge_plgs.RGB2XYZ", "classimagepy_1_1menus_1_1_image_1_1_color_1_1splitandmerge__plgs_1_1_r_g_b2_x_y_z.html", null ]
      ] ],
      [ "imagepy.menus.Image.Color.splitandmerge_plgs.RGB2Gray", "classimagepy_1_1menus_1_1_image_1_1_color_1_1splitandmerge__plgs_1_1_r_g_b2_gray.html", null ],
      [ "imagepy.menus.Image.Color.splitandmerge_plgs.SplitRGB", "classimagepy_1_1menus_1_1_image_1_1_color_1_1splitandmerge__plgs_1_1_split_r_g_b.html", null ],
      [ "imagepy.menus.Image.Color.splitandmerge_plgs.ToRGB", "classimagepy_1_1menus_1_1_image_1_1_color_1_1splitandmerge__plgs_1_1_to_r_g_b.html", [
        [ "imagepy.menus.Image.Color.splitandmerge_plgs.CIE2RGB", "classimagepy_1_1menus_1_1_image_1_1_color_1_1splitandmerge__plgs_1_1_c_i_e2_r_g_b.html", null ],
        [ "imagepy.menus.Image.Color.splitandmerge_plgs.HSV2RGB", "classimagepy_1_1menus_1_1_image_1_1_color_1_1splitandmerge__plgs_1_1_h_s_v2_r_g_b.html", null ],
        [ "imagepy.menus.Image.Color.splitandmerge_plgs.Lab2RGB", "classimagepy_1_1menus_1_1_image_1_1_color_1_1splitandmerge__plgs_1_1_lab2_r_g_b.html", null ],
        [ "imagepy.menus.Image.Color.splitandmerge_plgs.LUV2RGB", "classimagepy_1_1menus_1_1_image_1_1_color_1_1splitandmerge__plgs_1_1_l_u_v2_r_g_b.html", null ],
        [ "imagepy.menus.Image.Color.splitandmerge_plgs.MergeRGB", "classimagepy_1_1menus_1_1_image_1_1_color_1_1splitandmerge__plgs_1_1_merge_r_g_b.html", null ],
        [ "imagepy.menus.Image.Color.splitandmerge_plgs.XYZ2RGB", "classimagepy_1_1menus_1_1_image_1_1_color_1_1splitandmerge__plgs_1_1_x_y_z2_r_g_b.html", null ]
      ] ],
      [ "imagepy.menus.Image.crop_plg.Plugin", "classimagepy_1_1menus_1_1_image_1_1crop__plg_1_1_plugin.html", null ],
      [ "imagepy.menus.Image.duplicate_plg.Duplicate", "classimagepy_1_1menus_1_1_image_1_1duplicate__plg_1_1_duplicate.html", null ],
      [ "imagepy.menus.Image.duplicate_plg.Rename", "classimagepy_1_1menus_1_1_image_1_1duplicate__plg_1_1_rename.html", null ],
      [ "imagepy.menus.Image.Mark.mark_plgs.Clear", "classimagepy_1_1menus_1_1_image_1_1_mark_1_1mark__plgs_1_1_clear.html", null ],
      [ "imagepy.menus.Image.Mark.mark_plgs.Open", "classimagepy_1_1menus_1_1_image_1_1_mark_1_1mark__plgs_1_1_open.html", null ],
      [ "imagepy.menus.Image.Mark.mark_plgs.Save", "classimagepy_1_1menus_1_1_image_1_1_mark_1_1mark__plgs_1_1_save.html", null ],
      [ "imagepy.menus.Image.resize_plg.Plugin", "classimagepy_1_1menus_1_1_image_1_1resize__plg_1_1_plugin.html", null ],
      [ "imagepy.menus.Image.setscale_plg.Plugin", "classimagepy_1_1menus_1_1_image_1_1setscale__plg_1_1_plugin.html", null ],
      [ "imagepy.menus.Image.Stack.orthogonal_plg.Plugin", "classimagepy_1_1menus_1_1_image_1_1_stack_1_1orthogonal__plg_1_1_plugin.html", null ],
      [ "imagepy.menus.Image.Stack.stack_plgs.Add", "classimagepy_1_1menus_1_1_image_1_1_stack_1_1stack__plgs_1_1_add.html", null ],
      [ "imagepy.menus.Image.Stack.stack_plgs.Delete", "classimagepy_1_1menus_1_1_image_1_1_stack_1_1stack__plgs_1_1_delete.html", null ],
      [ "imagepy.menus.Image.Stack.stack_plgs.Next", "classimagepy_1_1menus_1_1_image_1_1_stack_1_1stack__plgs_1_1_next.html", null ],
      [ "imagepy.menus.Image.Stack.stack_plgs.Pre", "classimagepy_1_1menus_1_1_image_1_1_stack_1_1stack__plgs_1_1_pre.html", null ],
      [ "imagepy.menus.Image.Stack.stack_plgs.SetSlice", "classimagepy_1_1menus_1_1_image_1_1_stack_1_1stack__plgs_1_1_set_slice.html", null ],
      [ "imagepy.menus.Image.Stack.stack_plgs.Sub", "classimagepy_1_1menus_1_1_image_1_1_stack_1_1stack__plgs_1_1_sub.html", null ],
      [ "imagepy.menus.Image.Type.convert_plg.To8bit", "classimagepy_1_1menus_1_1_image_1_1_type_1_1convert__plg_1_1_to8bit.html", null ],
      [ "imagepy.menus.Image.Type.convert_plg.ToFloat32", "classimagepy_1_1menus_1_1_image_1_1_type_1_1convert__plg_1_1_to_float32.html", null ],
      [ "imagepy.menus.Image.Type.convert_plg.ToFloat64", "classimagepy_1_1menus_1_1_image_1_1_type_1_1convert__plg_1_1_to_float64.html", null ],
      [ "imagepy.menus.Image.Type.convert_plg.ToInt32", "classimagepy_1_1menus_1_1_image_1_1_type_1_1convert__plg_1_1_to_int32.html", null ],
      [ "imagepy.menus.Image.Type.convert_plg.ToRGB", "classimagepy_1_1menus_1_1_image_1_1_type_1_1convert__plg_1_1_to_r_g_b.html", null ],
      [ "imagepy.menus.Image.Type.convert_plg.ToUint16", "classimagepy_1_1menus_1_1_image_1_1_type_1_1convert__plg_1_1_to_uint16.html", null ],
      [ "imagepy.menus.Image.Type.tostack_plg.ToList", "classimagepy_1_1menus_1_1_image_1_1_type_1_1tostack__plg_1_1_to_list.html", null ],
      [ "imagepy.menus.Image.Type.tostack_plg.ToStack", "classimagepy_1_1menus_1_1_image_1_1_type_1_1tostack__plg_1_1_to_stack.html", null ],
      [ "imagepy.menus.Kit3D.Analysis 3D.pixelstatistic_plgs.Frequence", "classimagepy_1_1menus_1_1_kit3_d_1_1_analysis_013_d_1_1pixelstatistic__plgs_1_1_frequence.html", null ],
      [ "imagepy.menus.Kit3D.Analysis 3D.pixelstatistic_plgs.Statistic", "classimagepy_1_1menus_1_1_kit3_d_1_1_analysis_013_d_1_1pixelstatistic__plgs_1_1_statistic.html", null ],
      [ "imagepy.menus.Kit3D.Analysis 3D.regionprops3d_plgs.RegionCounter", "classimagepy_1_1menus_1_1_kit3_d_1_1_analysis_013_d_1_1regionprops3d__plgs_1_1_region_counter.html", null ],
      [ "imagepy.menus.Kit3D.Analysis 3D.regionprops3d_plgs.RegionFilter", "classimagepy_1_1menus_1_1_kit3_d_1_1_analysis_013_d_1_1regionprops3d__plgs_1_1_region_filter.html", null ],
      [ "imagepy.menus.Kit3D.Analysis 3D.regionprops3d_plgs.RegionLabel", "classimagepy_1_1menus_1_1_kit3_d_1_1_analysis_013_d_1_1regionprops3d__plgs_1_1_region_label.html", null ],
      [ "imagepy.menus.Kit3D.Binary 3D.binary3d_plgs.Closing", "classimagepy_1_1menus_1_1_kit3_d_1_1_binary_013_d_1_1binary3d__plgs_1_1_closing.html", null ],
      [ "imagepy.menus.Kit3D.Binary 3D.binary3d_plgs.Dilation", "classimagepy_1_1menus_1_1_kit3_d_1_1_binary_013_d_1_1binary3d__plgs_1_1_dilation.html", null ],
      [ "imagepy.menus.Kit3D.Binary 3D.binary3d_plgs.Distance3D", "classimagepy_1_1menus_1_1_kit3_d_1_1_binary_013_d_1_1binary3d__plgs_1_1_distance3_d.html", null ],
      [ "imagepy.menus.Kit3D.Binary 3D.binary3d_plgs.Erosion", "classimagepy_1_1menus_1_1_kit3_d_1_1_binary_013_d_1_1binary3d__plgs_1_1_erosion.html", null ],
      [ "imagepy.menus.Kit3D.Binary 3D.binary3d_plgs.FillHole", "classimagepy_1_1menus_1_1_kit3_d_1_1_binary_013_d_1_1binary3d__plgs_1_1_fill_hole.html", null ],
      [ "imagepy.menus.Kit3D.Binary 3D.binary3d_plgs.Opening", "classimagepy_1_1menus_1_1_kit3_d_1_1_binary_013_d_1_1binary3d__plgs_1_1_opening.html", null ],
      [ "imagepy.menus.Kit3D.Binary 3D.binary3d_plgs.Skeleton3D", "classimagepy_1_1menus_1_1_kit3_d_1_1_binary_013_d_1_1binary3d__plgs_1_1_skeleton3_d.html", null ],
      [ "imagepy.menus.Kit3D.Binary 3D.binary3d_plgs.Watershed", "classimagepy_1_1menus_1_1_kit3_d_1_1_binary_013_d_1_1binary3d__plgs_1_1_watershed.html", null ],
      [ "imagepy.menus.Kit3D.Features 3D.ridge_plgs.Frangi", "classimagepy_1_1menus_1_1_kit3_d_1_1_features_013_d_1_1ridge__plgs_1_1_frangi.html", null ],
      [ "imagepy.menus.Kit3D.Features 3D.ridge_plgs.Hessian", "classimagepy_1_1menus_1_1_kit3_d_1_1_features_013_d_1_1ridge__plgs_1_1_hessian.html", null ],
      [ "imagepy.menus.Kit3D.Features 3D.ridge_plgs.Meijering", "classimagepy_1_1menus_1_1_kit3_d_1_1_features_013_d_1_1ridge__plgs_1_1_meijering.html", null ],
      [ "imagepy.menus.Kit3D.Features 3D.ridge_plgs.Sato", "classimagepy_1_1menus_1_1_kit3_d_1_1_features_013_d_1_1ridge__plgs_1_1_sato.html", null ],
      [ "imagepy.menus.Kit3D.Filters 3D.filters3d_plgs.Gaussian3D", "classimagepy_1_1menus_1_1_kit3_d_1_1_filters_013_d_1_1filters3d__plgs_1_1_gaussian3_d.html", null ],
      [ "imagepy.menus.Kit3D.Filters 3D.filters3d_plgs.Sobel3D", "classimagepy_1_1menus_1_1_kit3_d_1_1_filters_013_d_1_1filters3d__plgs_1_1_sobel3_d.html", null ],
      [ "imagepy.menus.Kit3D.Filters 3D.filters3d_plgs.Uniform3D", "classimagepy_1_1menus_1_1_kit3_d_1_1_filters_013_d_1_1filters3d__plgs_1_1_uniform3_d.html", null ],
      [ "imagepy.menus.Kit3D.Filters 3D.filters3d_plgs.USM3D", "classimagepy_1_1menus_1_1_kit3_d_1_1_filters_013_d_1_1filters3d__plgs_1_1_u_s_m3_d.html", null ],
      [ "imagepy.menus.Kit3D.Network 3D.toolkit3d_plgs.Angles", "classimagepy_1_1menus_1_1_kit3_d_1_1_network_013_d_1_1toolkit3d__plgs_1_1_angles.html", null ],
      [ "imagepy.menus.Kit3D.Network 3D.toolkit3d_plgs.BuildGraph", "classimagepy_1_1menus_1_1_kit3_d_1_1_network_013_d_1_1toolkit3d__plgs_1_1_build_graph.html", null ],
      [ "imagepy.menus.Kit3D.Network 3D.toolkit3d_plgs.CutBranch", "classimagepy_1_1menus_1_1_kit3_d_1_1_network_013_d_1_1toolkit3d__plgs_1_1_cut_branch.html", null ],
      [ "imagepy.menus.Kit3D.Network 3D.toolkit3d_plgs.Remove2Node", "classimagepy_1_1menus_1_1_kit3_d_1_1_network_013_d_1_1toolkit3d__plgs_1_1_remove2_node.html", null ],
      [ "imagepy.menus.Kit3D.Network 3D.toolkit3d_plgs.RemoveIsolate", "classimagepy_1_1menus_1_1_kit3_d_1_1_network_013_d_1_1toolkit3d__plgs_1_1_remove_isolate.html", null ],
      [ "imagepy.menus.Kit3D.Network 3D.toolkit3d_plgs.Show3DGraph", "classimagepy_1_1menus_1_1_kit3_d_1_1_network_013_d_1_1toolkit3d__plgs_1_1_show3_d_graph.html", null ],
      [ "imagepy.menus.Kit3D.Network 3D.toolkit3d_plgs.Show3DGraphR", "classimagepy_1_1menus_1_1_kit3_d_1_1_network_013_d_1_1toolkit3d__plgs_1_1_show3_d_graph_r.html", null ],
      [ "imagepy.menus.Kit3D.Network 3D.toolkit3d_plgs.Skeleton3D", "classimagepy_1_1menus_1_1_kit3_d_1_1_network_013_d_1_1toolkit3d__plgs_1_1_skeleton3_d.html", null ],
      [ "imagepy.menus.Kit3D.Network 3D.toolkit3d_plgs.Statistic", "classimagepy_1_1menus_1_1_kit3_d_1_1_network_013_d_1_1toolkit3d__plgs_1_1_statistic.html", null ],
      [ "imagepy.menus.Kit3D.Network 3D.toolkit3d_plgs.Sumerise", "classimagepy_1_1menus_1_1_kit3_d_1_1_network_013_d_1_1toolkit3d__plgs_1_1_sumerise.html", null ],
      [ "imagepy.menus.Kit3D.Viewer 3D.colorpts_plg.Plugin", "classimagepy_1_1menus_1_1_kit3_d_1_1_viewer_013_d_1_1colorpts__plg_1_1_plugin.html", null ],
      [ "imagepy.menus.Kit3D.Viewer 3D.surface_plgs.ImageCube", "classimagepy_1_1menus_1_1_kit3_d_1_1_viewer_013_d_1_1surface__plgs_1_1_image_cube.html", null ],
      [ "imagepy.menus.Kit3D.Viewer 3D.surface_plgs.Surface2D", "classimagepy_1_1menus_1_1_kit3_d_1_1_viewer_013_d_1_1surface__plgs_1_1_surface2_d.html", null ],
      [ "imagepy.menus.Plugins.Games.drawstep_plg.Plugin", "classimagepy_1_1menus_1_1_plugins_1_1_games_1_1drawstep__plg_1_1_plugin.html", null ],
      [ "imagepy.menus.Plugins.New.demo_simple.Plugin", "classimagepy_1_1menus_1_1_plugins_1_1_new_1_1demo__simple_1_1_plugin.html", null ],
      [ "imagepy.menus.Plugins.StackReg.stackreg_plgs.Register", "classimagepy_1_1menus_1_1_plugins_1_1_stack_reg_1_1stackreg__plgs_1_1_register.html", null ],
      [ "imagepy.menus.Plugins.StackReg.stackreg_plgs.Transform", "classimagepy_1_1menus_1_1_plugins_1_1_stack_reg_1_1stackreg__plgs_1_1_transform.html", null ],
      [ "imagepy.menus.Process.calculator_plg.Plugin", "classimagepy_1_1menus_1_1_process_1_1calculator__plg_1_1_plugin.html", null ],
      [ "imagepy.menus.Process.FFT.fft_plgs.FFT", "classimagepy_1_1menus_1_1_process_1_1_f_f_t_1_1fft__plgs_1_1_f_f_t.html", null ],
      [ "imagepy.menus.Process.FFT.fft_plgs.IFFT", "classimagepy_1_1menus_1_1_process_1_1_f_f_t_1_1fft__plgs_1_1_i_f_f_t.html", null ],
      [ "imagepy.menus.Process.FFT.fft_plgs.LogPower", "classimagepy_1_1menus_1_1_process_1_1_f_f_t_1_1fft__plgs_1_1_log_power.html", null ],
      [ "imagepy.menus.Process.Segment.graph_plgs.MergeHierarchical", "classimagepy_1_1menus_1_1_process_1_1_segment_1_1graph__plgs_1_1_merge_hierarchical.html", null ],
      [ "imagepy.menus.Process.Segment.graph_plgs.NormalCut", "classimagepy_1_1menus_1_1_process_1_1_segment_1_1graph__plgs_1_1_normal_cut.html", null ],
      [ "imagepy.menus.Process.Segment.graph_plgs.RagThreshold", "classimagepy_1_1menus_1_1_process_1_1_segment_1_1graph__plgs_1_1_rag_threshold.html", null ],
      [ "imagepy.menus.Process.Segment.shift_plgs.FelzenszwalbLab", "classimagepy_1_1menus_1_1_process_1_1_segment_1_1shift__plgs_1_1_felzenszwalb_lab.html", null ],
      [ "imagepy.menus.Process.Segment.shift_plgs.QuickshiftLab", "classimagepy_1_1menus_1_1_process_1_1_segment_1_1shift__plgs_1_1_quickshift_lab.html", null ],
      [ "imagepy.menus.Process.Segment.shift_plgs.SLICLab", "classimagepy_1_1menus_1_1_process_1_1_segment_1_1shift__plgs_1_1_s_l_i_c_lab.html", null ],
      [ "imagepy.menus.Selection.select_plg.Add2Manager", "classimagepy_1_1menus_1_1_selection_1_1select__plg_1_1_add2_manager.html", null ],
      [ "imagepy.menus.Selection.select_plg.Box", "classimagepy_1_1menus_1_1_selection_1_1select__plg_1_1_box.html", null ],
      [ "imagepy.menus.Selection.select_plg.Clip", "classimagepy_1_1menus_1_1_selection_1_1select__plg_1_1_clip.html", null ],
      [ "imagepy.menus.Selection.select_plg.Convex", "classimagepy_1_1menus_1_1_selection_1_1select__plg_1_1_convex.html", null ],
      [ "imagepy.menus.Selection.select_plg.Diff", "classimagepy_1_1menus_1_1_selection_1_1select__plg_1_1_diff.html", null ],
      [ "imagepy.menus.Selection.select_plg.Inflate", "classimagepy_1_1menus_1_1_selection_1_1select__plg_1_1_inflate.html", null ],
      [ "imagepy.menus.Selection.select_plg.Intersect", "classimagepy_1_1menus_1_1_selection_1_1select__plg_1_1_intersect.html", null ],
      [ "imagepy.menus.Selection.select_plg.Invert", "classimagepy_1_1menus_1_1_selection_1_1select__plg_1_1_invert.html", null ],
      [ "imagepy.menus.Selection.select_plg.LoadRoi", "classimagepy_1_1menus_1_1_selection_1_1select__plg_1_1_load_roi.html", null ],
      [ "imagepy.menus.Selection.select_plg.Open", "classimagepy_1_1menus_1_1_selection_1_1select__plg_1_1_open.html", null ],
      [ "imagepy.menus.Selection.select_plg.RemoveFManager", "classimagepy_1_1menus_1_1_selection_1_1select__plg_1_1_remove_f_manager.html", null ],
      [ "imagepy.menus.Selection.select_plg.Save", "classimagepy_1_1menus_1_1_selection_1_1select__plg_1_1_save.html", null ],
      [ "imagepy.menus.Selection.select_plg.SelectAll", "classimagepy_1_1menus_1_1_selection_1_1select__plg_1_1_select_all.html", null ],
      [ "imagepy.menus.Selection.select_plg.SelectNone", "classimagepy_1_1menus_1_1_selection_1_1select__plg_1_1_select_none.html", null ],
      [ "imagepy.menus.Selection.select_plg.Shrink", "classimagepy_1_1menus_1_1_selection_1_1select__plg_1_1_shrink.html", null ],
      [ "imagepy.menus.Selection.select_plg.SymDiff", "classimagepy_1_1menus_1_1_selection_1_1select__plg_1_1_sym_diff.html", null ],
      [ "imagepy.menus.Selection.select_plg.Union", "classimagepy_1_1menus_1_1_selection_1_1select__plg_1_1_union.html", null ],
      [ "imagepy.tools.Draw.flood3d_tol.FloodFill3D", "classimagepy_1_1tools_1_1_draw_1_1flood3d__tol_1_1_flood_fill3_d.html", null ],
      [ "imagepy.tools.Toolkit3D.flood3d_tol.FloodFill3D", "classimagepy_1_1tools_1_1_toolkit3_d_1_1flood3d__tol_1_1_flood_fill3_d.html", null ]
    ] ],
    [ "imagepy.core.myvi.manager.Surface", "classimagepy_1_1core_1_1myvi_1_1manager_1_1_surface.html", null ],
    [ "imagepy.core.engine.table.Table", "classimagepy_1_1core_1_1engine_1_1table_1_1_table.html", [
      [ "imagepy.core.util.tableio.Writer", "classimagepy_1_1core_1_1util_1_1tableio_1_1_writer.html", null ],
      [ "imagepy.menus.Kit3D.Viewer 3D.tablepoints_plg.Plugin", "classimagepy_1_1menus_1_1_kit3_d_1_1_viewer_013_d_1_1tablepoints__plg_1_1_plugin.html", null ],
      [ "imagepy.menus.Table.Basic Operator.basic_plgs.AddCol", "classimagepy_1_1menus_1_1_table_1_1_basic_01_operator_1_1basic__plgs_1_1_add_col.html", null ],
      [ "imagepy.menus.Table.Basic Operator.basic_plgs.AppendRow", "classimagepy_1_1menus_1_1_table_1_1_basic_01_operator_1_1basic__plgs_1_1_append_row.html", null ],
      [ "imagepy.menus.Table.Basic Operator.basic_plgs.Corp", "classimagepy_1_1menus_1_1_table_1_1_basic_01_operator_1_1basic__plgs_1_1_corp.html", null ],
      [ "imagepy.menus.Table.Basic Operator.basic_plgs.DeleteCol", "classimagepy_1_1menus_1_1_table_1_1_basic_01_operator_1_1basic__plgs_1_1_delete_col.html", null ],
      [ "imagepy.menus.Table.Basic Operator.basic_plgs.DeleteRow", "classimagepy_1_1menus_1_1_table_1_1_basic_01_operator_1_1basic__plgs_1_1_delete_row.html", null ],
      [ "imagepy.menus.Table.Basic Operator.basic_plgs.Duplicate", "classimagepy_1_1menus_1_1_table_1_1_basic_01_operator_1_1basic__plgs_1_1_duplicate.html", null ],
      [ "imagepy.menus.Table.Basic Operator.basic_plgs.Transpose", "classimagepy_1_1menus_1_1_table_1_1_basic_01_operator_1_1basic__plgs_1_1_transpose.html", null ],
      [ "imagepy.menus.Table.Chart.plot_plgs.Area", "classimagepy_1_1menus_1_1_table_1_1_chart_1_1plot__plgs_1_1_area.html", null ],
      [ "imagepy.menus.Table.Chart.plot_plgs.Bar", "classimagepy_1_1menus_1_1_table_1_1_chart_1_1plot__plgs_1_1_bar.html", null ],
      [ "imagepy.menus.Table.Chart.plot_plgs.Box", "classimagepy_1_1menus_1_1_table_1_1_chart_1_1plot__plgs_1_1_box.html", null ],
      [ "imagepy.menus.Table.Chart.plot_plgs.Hist", "classimagepy_1_1menus_1_1_table_1_1_chart_1_1plot__plgs_1_1_hist.html", null ],
      [ "imagepy.menus.Table.Chart.plot_plgs.Pie", "classimagepy_1_1menus_1_1_table_1_1_chart_1_1plot__plgs_1_1_pie.html", null ],
      [ "imagepy.menus.Table.Chart.plot_plgs.Plot", "classimagepy_1_1menus_1_1_table_1_1_chart_1_1plot__plgs_1_1_plot.html", null ],
      [ "imagepy.menus.Table.Chart.plot_plgs.Scatter", "classimagepy_1_1menus_1_1_table_1_1_chart_1_1plot__plgs_1_1_scatter.html", null ],
      [ "imagepy.menus.Table.Selection.select_plgs.Select", "classimagepy_1_1menus_1_1_table_1_1_selection_1_1select__plgs_1_1_select.html", null ],
      [ "imagepy.menus.Table.Signal.signal_plgs.Statistic", "classimagepy_1_1menus_1_1_table_1_1_signal_1_1signal__plgs_1_1_statistic.html", null ],
      [ "imagepy.menus.Table.Statistic.frequency_plgs.Count", "classimagepy_1_1menus_1_1_table_1_1_statistic_1_1frequency__plgs_1_1_count.html", null ],
      [ "imagepy.menus.Table.Statistic.frequency_plgs.Frequency", "classimagepy_1_1menus_1_1_table_1_1_statistic_1_1frequency__plgs_1_1_frequency.html", null ],
      [ "imagepy.menus.Table.Statistic.sort_plg.Plugin", "classimagepy_1_1menus_1_1_table_1_1_statistic_1_1sort__plg_1_1_plugin.html", null ],
      [ "imagepy.menus.Table.Statistic.statistic_plgs.GroupStatistic", "classimagepy_1_1menus_1_1_table_1_1_statistic_1_1statistic__plgs_1_1_group_statistic.html", null ],
      [ "imagepy.menus.Table.Statistic.statistic_plgs.Statistic", "classimagepy_1_1menus_1_1_table_1_1_statistic_1_1statistic__plgs_1_1_statistic.html", null ]
    ] ],
    [ "imagepy.core.manager.windowmanager.TableManager", "classimagepy_1_1core_1_1manager_1_1windowmanager_1_1_table_manager.html", null ],
    [ "imagepy.core.wraper.tableplus.TablePlus", "classimagepy_1_1core_1_1wraper_1_1tableplus_1_1_table_plus.html", null ],
    [ "imagepy.core.manager.taskmanager.TaskManager", "classimagepy_1_1core_1_1manager_1_1taskmanager_1_1_task_manager.html", null ],
    [ "imagepy.core.manager.windowmanager.TextLogManager", "classimagepy_1_1core_1_1manager_1_1windowmanager_1_1_text_log_manager.html", null ],
    [ "ThresholdPlg", null, [
      [ "imagepy.menus.Process.Threshold.threshold_plgs.SimpleThreshold", "classimagepy_1_1menus_1_1_process_1_1_threshold_1_1threshold__plgs_1_1_simple_threshold.html", null ]
    ] ],
    [ "imagepy.core.engine.tool.Tool", "classimagepy_1_1core_1_1engine_1_1tool_1_1_tool.html", [
      [ "imagepy.menus.Edit.edit_plg.PasteMove", "classimagepy_1_1menus_1_1_edit_1_1edit__plg_1_1_paste_move.html", null ],
      [ "imagepy.menus.Image.Stack.orthogonal_plg.Orthogonal", "classimagepy_1_1menus_1_1_image_1_1_stack_1_1orthogonal__plg_1_1_orthogonal.html", null ],
      [ "imagepy.menus.Plugins.Games.lifegame_plg.Painter", "classimagepy_1_1menus_1_1_plugins_1_1_games_1_1lifegame__plg_1_1_painter.html", null ],
      [ "imagepy.menus.Plugins.New.demo_tool.Plugin", "classimagepy_1_1menus_1_1_plugins_1_1_new_1_1demo__tool_1_1_plugin.html", null ],
      [ "imagepy.tools.Draw.flood3d_tol.Plugin", "classimagepy_1_1tools_1_1_draw_1_1flood3d__tol_1_1_plugin.html", null ],
      [ "imagepy.tools.Draw.floodfill_tol.Plugin", "classimagepy_1_1tools_1_1_draw_1_1floodfill__tol_1_1_plugin.html", null ],
      [ "imagepy.tools.Draw.magic_tol.Plugin", "classimagepy_1_1tools_1_1_draw_1_1magic__tol_1_1_plugin.html", null ],
      [ "imagepy.tools.Measure.angle2_tol.Plugin", "classimagepy_1_1tools_1_1_measure_1_1angle2__tol_1_1_plugin.html", null ],
      [ "imagepy.tools.Measure.angle_tol.Plugin", "classimagepy_1_1tools_1_1_measure_1_1angle__tol_1_1_plugin.html", null ],
      [ "imagepy.tools.Measure.area_tol.Plugin", "classimagepy_1_1tools_1_1_measure_1_1area__tol_1_1_plugin.html", null ],
      [ "imagepy.tools.Measure.coordinate_tol.Plugin", "classimagepy_1_1tools_1_1_measure_1_1coordinate__tol_1_1_plugin.html", null ],
      [ "imagepy.tools.Measure.distance_tol.Plugin", "classimagepy_1_1tools_1_1_measure_1_1distance__tol_1_1_plugin.html", null ],
      [ "imagepy.tools.Measure.profile_tol.Plugin", "classimagepy_1_1tools_1_1_measure_1_1profile__tol_1_1_plugin.html", null ],
      [ "imagepy.tools.Measure.setting_tol.Plugin", "classimagepy_1_1tools_1_1_measure_1_1setting__tol_1_1_plugin.html", null ],
      [ "imagepy.tools.Network.graphcut_tol.Plugin", "classimagepy_1_1tools_1_1_network_1_1graphcut__tol_1_1_plugin.html", null ],
      [ "imagepy.tools.Network.graphpen_tol.Plugin", "classimagepy_1_1tools_1_1_network_1_1graphpen__tol_1_1_plugin.html", null ],
      [ "imagepy.tools.Standard.colorpicker_tol.Plugin", "classimagepy_1_1tools_1_1_standard_1_1colorpicker__tol_1_1_plugin.html", null ],
      [ "imagepy.tools.Standard.freearea_tol.Plugin", "classimagepy_1_1tools_1_1_standard_1_1freearea__tol_1_1_plugin.html", null ],
      [ "imagepy.tools.Standard.freeline_tol.Plugin", "classimagepy_1_1tools_1_1_standard_1_1freeline__tol_1_1_plugin.html", null ],
      [ "imagepy.tools.Standard.line_tol.Plugin", "classimagepy_1_1tools_1_1_standard_1_1line__tol_1_1_plugin.html", null ],
      [ "imagepy.tools.Standard.magic_tol.Plugin", "classimagepy_1_1tools_1_1_standard_1_1magic__tol_1_1_plugin.html", null ],
      [ "imagepy.tools.Standard.move_tol.Plugin", "classimagepy_1_1tools_1_1_standard_1_1move__tol_1_1_plugin.html", null ],
      [ "imagepy.tools.Standard.oval_tol.Plugin", "classimagepy_1_1tools_1_1_standard_1_1oval__tol_1_1_plugin.html", null ],
      [ "imagepy.tools.Standard.painter_tol.Plugin", "classimagepy_1_1tools_1_1_standard_1_1painter__tol_1_1_plugin.html", null ],
      [ "imagepy.tools.Standard.point_tol.Plugin", "classimagepy_1_1tools_1_1_standard_1_1point__tol_1_1_plugin.html", null ],
      [ "imagepy.tools.Standard.polygon_tol.Plugin", "classimagepy_1_1tools_1_1_standard_1_1polygon__tol_1_1_plugin.html", null ],
      [ "imagepy.tools.Standard.rectangle_tol.Plugin", "classimagepy_1_1tools_1_1_standard_1_1rectangle__tol_1_1_plugin.html", null ],
      [ "imagepy.tools.Standard.scale_tol.Plugin", "classimagepy_1_1tools_1_1_standard_1_1scale__tol_1_1_plugin.html", null ],
      [ "imagepy.tools.Toolkit3D.cursor3d_tol.Plugin", "classimagepy_1_1tools_1_1_toolkit3_d_1_1cursor3d__tol_1_1_plugin.html", null ],
      [ "imagepy.tools.Toolkit3D.flood3d_tol.Plugin", "classimagepy_1_1tools_1_1_toolkit3_d_1_1flood3d__tol_1_1_plugin.html", null ],
      [ "imagepy.tools.Transform.rotate_tol.RotateTool", "classimagepy_1_1tools_1_1_transform_1_1rotate__tol_1_1_rotate_tool.html", null ],
      [ "imagepy.tools.Transform.scale_tol.ScaleTool", "classimagepy_1_1tools_1_1_transform_1_1scale__tol_1_1_scale_tool.html", null ]
    ] ],
    [ "imagepy.core.manager.pluginmanager.ToolsManager", "classimagepy_1_1core_1_1manager_1_1pluginmanager_1_1_tools_manager.html", null ],
    [ "imagepy.core.manager.iomanager.ViewerManager", "classimagepy_1_1core_1_1manager_1_1iomanager_1_1_viewer_manager.html", null ],
    [ "imagepy.ui.canvasframe.VirturlCanvas", "classimagepy_1_1ui_1_1canvasframe_1_1_virturl_canvas.html", null ],
    [ "imagepy.core.engine.widget.Widget", "classimagepy_1_1core_1_1engine_1_1widget_1_1_widget.html", null ],
    [ "imagepy.core.manager.pluginmanager.WidgetsManager", "classimagepy_1_1core_1_1manager_1_1pluginmanager_1_1_widgets_manager.html", null ],
    [ "imagepy.core.manager.windowmanager.WindowsManager", "classimagepy_1_1core_1_1manager_1_1windowmanager_1_1_windows_manager.html", null ],
    [ "imagepy.core.engine.workflow.WorkFlow", "classimagepy_1_1core_1_1engine_1_1workflow_1_1_work_flow.html", null ],
    [ "Writer", null, [
      [ "imagepy.menus.Table.Table IO.tableio_plgs.SaveCSV", "classimagepy_1_1menus_1_1_table_1_1_table_01_i_o_1_1tableio__plgs_1_1_save_c_s_v.html", null ],
      [ "imagepy.menus.Table.Table IO.tableio_plgs.SaveExcel", "classimagepy_1_1menus_1_1_table_1_1_table_01_i_o_1_1tableio__plgs_1_1_save_excel.html", null ]
    ] ],
    [ "Writer", null, [
      [ "imagepy.menus.File.BMP.bmp_plgs.SaveFile", "classimagepy_1_1menus_1_1_file_1_1_b_m_p_1_1bmp__plgs_1_1_save_file.html", null ],
      [ "imagepy.menus.File.DAT.dat_plgs.SaveFile", "classimagepy_1_1menus_1_1_file_1_1_d_a_t_1_1dat__plgs_1_1_save_file.html", null ],
      [ "imagepy.menus.File.GIF.gif_plgs.SaveFile", "classimagepy_1_1menus_1_1_file_1_1_g_i_f_1_1gif__plgs_1_1_save_file.html", null ],
      [ "imagepy.menus.File.JPG.jpg_plgs.SaveFile", "classimagepy_1_1menus_1_1_file_1_1_j_p_g_1_1jpg__plgs_1_1_save_file.html", null ],
      [ "imagepy.menus.File.MAT.mat_plgs.Save3D", "classimagepy_1_1menus_1_1_file_1_1_m_a_t_1_1mat__plgs_1_1_save3_d.html", null ],
      [ "imagepy.menus.File.MAT.mat_plgs.SaveFile", "classimagepy_1_1menus_1_1_file_1_1_m_a_t_1_1mat__plgs_1_1_save_file.html", null ],
      [ "imagepy.menus.File.Numpy.ndarray_plgs.Save3D", "classimagepy_1_1menus_1_1_file_1_1_numpy_1_1ndarray__plgs_1_1_save3_d.html", null ],
      [ "imagepy.menus.File.Numpy.ndarray_plgs.SaveFile", "classimagepy_1_1menus_1_1_file_1_1_numpy_1_1ndarray__plgs_1_1_save_file.html", null ],
      [ "imagepy.menus.File.PNG.png_plgs.SaveFile", "classimagepy_1_1menus_1_1_file_1_1_p_n_g_1_1png__plgs_1_1_save_file.html", null ],
      [ "imagepy.menus.File.save_plg.SaveImage", "classimagepy_1_1menus_1_1_file_1_1save__plg_1_1_save_image.html", null ],
      [ "imagepy.menus.File.save_plg.WindowCapture", "classimagepy_1_1menus_1_1_file_1_1save__plg_1_1_window_capture.html", null ],
      [ "imagepy.menus.File.TIF.tif3d_plgs.Save", "classimagepy_1_1menus_1_1_file_1_1_t_i_f_1_1tif3d__plgs_1_1_save.html", null ],
      [ "imagepy.menus.File.TIF.tif_plgs.SaveFile", "classimagepy_1_1menus_1_1_file_1_1_t_i_f_1_1tif__plgs_1_1_save_file.html", null ]
    ] ],
    [ "imagepy.core.manager.iomanager.WriterManager", "classimagepy_1_1core_1_1manager_1_1iomanager_1_1_writer_manager.html", null ],
    [ "imagepy.core.manager.windowmanager.WTableManager", "classimagepy_1_1core_1_1manager_1_1windowmanager_1_1_w_table_manager.html", null ]
];