var searchData=
[
  ['calendar',['Calendar',['../classimagepy_1_1menus_1_1_table_1_1_universal_01_generator_1_1gnerator__plgs_1_1_calendar.html',1,'imagepy::menus::Table::Universal Generator::gnerator_plgs']]],
  ['canny',['Canny',['../classimagepy_1_1menus_1_1_process_1_1_features_1_1edge__plgs_1_1_canny.html',1,'imagepy::menus::Process::Features::edge_plgs']]],
  ['canvas',['Canvas',['../classimagepy_1_1ui_1_1canvas_1_1_canvas.html',1,'imagepy.ui.canvas.Canvas'],['../classimagepy_1_1ui_1_1canvasframe_1_1_virturl_canvas_1_1_canvas.html',1,'imagepy.ui.canvasframe.VirturlCanvas.Canvas']]],
  ['canvas3d',['Canvas3D',['../classimagepy_1_1core_1_1myvi_1_1canvas3d_1_1_canvas3_d.html',1,'imagepy::core::myvi::canvas3d']]],
  ['canvasframe',['CanvasFrame',['../classimagepy_1_1ui_1_1canvasframe_1_1_canvas_frame.html',1,'imagepy::ui::canvasframe']]],
  ['canvasnotebook',['CanvasNoteBook',['../classimagepy_1_1ui_1_1canvasframe_1_1_canvas_note_book.html',1,'imagepy::ui::canvasframe']]],
  ['canvaspanel',['CanvasPanel',['../classimagepy_1_1ui_1_1canvasframe_1_1_canvas_panel.html',1,'imagepy::ui::canvasframe']]],
  ['chanvese',['ChanVese',['../classimagepy_1_1menus_1_1_process_1_1_segment_1_1active__plgs_1_1_chan_vese.html',1,'imagepy::menus::Process::Segment::active_plgs']]],
  ['check',['Check',['../classimagepy_1_1ui_1_1widgets_1_1normal_1_1_check.html',1,'imagepy::ui::widgets::normal']]],
  ['choice',['Choice',['../classimagepy_1_1ui_1_1widgets_1_1normal_1_1_choice.html',1,'imagepy::ui::widgets::normal']]],
  ['choices',['Choices',['../classimagepy_1_1ui_1_1widgets_1_1normal_1_1_choices.html',1,'imagepy::ui::widgets::normal']]],
  ['cie2rgb',['CIE2RGB',['../classimagepy_1_1menus_1_1_image_1_1_color_1_1splitandmerge__plgs_1_1_c_i_e2_r_g_b.html',1,'imagepy::menus::Image::Color::splitandmerge_plgs']]],
  ['cleandictionary',['CleanDictionary',['../classimagepy_1_1menus_1_1_help_1_1_language_1_1language__plgs_1_1_clean_dictionary.html',1,'imagepy::menus::Help::Language::language_plgs']]],
  ['clear',['Clear',['../classimagepy_1_1menus_1_1_image_1_1_mark_1_1mark__plgs_1_1_clear.html',1,'imagepy.menus.Image.Mark.mark_plgs.Clear'],['../classimagepy_1_1menus_1_1_edit_1_1edit__plg_1_1_clear.html',1,'imagepy.menus.Edit.edit_plg.Clear']]],
  ['clearout',['ClearOut',['../classimagepy_1_1menus_1_1_edit_1_1edit__plg_1_1_clear_out.html',1,'imagepy::menus::Edit::edit_plg']]],
  ['clip',['Clip',['../classimagepy_1_1menus_1_1_selection_1_1select__plg_1_1_clip.html',1,'imagepy::menus::Selection::select_plg']]],
  ['clipboardmanager',['ClipBoardManager',['../classimagepy_1_1core_1_1manager_1_1clipbdmanager_1_1_clip_board_manager.html',1,'imagepy::core::manager::clipbdmanager']]],
  ['closing',['Closing',['../classimagepy_1_1menus_1_1_process_1_1_binary_1_1binary__plgs_1_1_closing.html',1,'imagepy.menus.Process.Binary.binary_plgs.Closing'],['../classimagepy_1_1menus_1_1_kit3_d_1_1_binary_013_d_1_1binary3d__plgs_1_1_closing.html',1,'imagepy.menus.Kit3D.Binary 3D.binary3d_plgs.Closing']]],
  ['cmappanel',['CMapPanel',['../classimagepy_1_1ui_1_1widgets_1_1cmappanel_1_1_c_map_panel.html',1,'imagepy::ui::widgets::cmappanel']]],
  ['cmapselctrl',['CMapSelCtrl',['../classimagepy_1_1ui_1_1widgets_1_1colormap_1_1_c_map_sel_ctrl.html',1,'imagepy::ui::widgets::colormap']]],
  ['cmapselpanel',['CMapSelPanel',['../classimagepy_1_1ui_1_1widgets_1_1colormap_1_1_c_map_sel_panel.html',1,'imagepy::ui::widgets::colormap']]],
  ['colorcluster',['ColorCluster',['../classimagepy_1_1menus_1_1_analysis_1_1_pixel_01_cluster_1_1cluster__plgs_1_1_color_cluster.html',1,'imagepy::menus::Analysis::Pixel Cluster::cluster_plgs']]],
  ['colorcluster3d',['ColorCluster3D',['../classimagepy_1_1menus_1_1_analysis_1_1_pixel_01_cluster_1_1cluster__plgs_1_1_color_cluster3_d.html',1,'imagepy::menus::Analysis::Pixel Cluster::cluster_plgs']]],
  ['colorctrl',['ColorCtrl',['../classimagepy_1_1ui_1_1widgets_1_1normal_1_1_color_ctrl.html',1,'imagepy::ui::widgets::normal']]],
  ['colormanager',['ColorManager',['../classimagepy_1_1core_1_1manager_1_1colormanager_1_1_color_manager.html',1,'imagepy::core::manager::colormanager']]],
  ['colormap',['ColorMap',['../classimagepy_1_1ui_1_1widgets_1_1advanced_1_1_color_map.html',1,'imagepy::ui::widgets::advanced']]],
  ['colorstatistic',['ColorStatistic',['../classimagepy_1_1menus_1_1_analysis_1_1_pixel_01_cluster_1_1statistic__plgs_1_1_color_statistic.html',1,'imagepy::menus::Analysis::Pixel Cluster::statistic_plgs']]],
  ['configmanager',['ConfigManager',['../classimagepy_1_1core_1_1manager_1_1configmanager_1_1_config_manager.html',1,'imagepy::core::manager::configmanager']]],
  ['convex',['Convex',['../classimagepy_1_1menus_1_1_process_1_1_binary_1_1binary__plgs_1_1_convex.html',1,'imagepy.menus.Process.Binary.binary_plgs.Convex'],['../classimagepy_1_1menus_1_1_selection_1_1select__plg_1_1_convex.html',1,'imagepy.menus.Selection.select_plg.Convex']]],
  ['coordinate',['Coordinate',['../classimagepy_1_1tools_1_1_measure_1_1coordinate__tol_1_1_coordinate.html',1,'imagepy::tools::Measure::coordinate_tol']]],
  ['copy',['Copy',['../classimagepy_1_1menus_1_1_edit_1_1edit__plg_1_1_copy.html',1,'imagepy::menus::Edit::edit_plg']]],
  ['corp',['Corp',['../classimagepy_1_1menus_1_1_table_1_1_basic_01_operator_1_1basic__plgs_1_1_corp.html',1,'imagepy::menus::Table::Basic Operator::basic_plgs']]],
  ['count',['Count',['../classimagepy_1_1menus_1_1_table_1_1_statistic_1_1frequency__plgs_1_1_count.html',1,'imagepy::menus::Table::Statistic::frequency_plgs']]],
  ['cross',['Cross',['../classimagepy_1_1menus_1_1_image_1_1_stack_1_1orthogonal__plg_1_1_cross.html',1,'imagepy::menus::Image::Stack::orthogonal_plg']]],
  ['curvepanel',['CurvePanel',['../classimagepy_1_1ui_1_1widgets_1_1curvepanel_1_1_curve_panel.html',1,'imagepy::ui::widgets::curvepanel']]],
  ['cutbranch',['CutBranch',['../classimagepy_1_1menus_1_1_analysis_1_1_skeleton_01_network_1_1graph__plgs_1_1_cut_branch.html',1,'imagepy.menus.Analysis.Skeleton Network.graph_plgs.CutBranch'],['../classimagepy_1_1menus_1_1_kit3_d_1_1_network_013_d_1_1toolkit3d__plgs_1_1_cut_branch.html',1,'imagepy.menus.Kit3D.Network 3D.toolkit3d_plgs.CutBranch']]],
  ['cutroi',['CutROI',['../classimagepy_1_1menus_1_1_analysis_1_1_skeleton_01_network_1_1graph__plgs_1_1_cut_r_o_i.html',1,'imagepy::menus::Analysis::Skeleton Network::graph_plgs']]],
  ['contribute_20document',['Contribute Document',['../md_menus__plugins__contribute__contribute__document.html',1,'']]],
  ['contribute_20plugin',['Contribute Plugin',['../md_menus__plugins__contribute__contribute__plugin.html',1,'']]]
];
